### ISSUE TITLE
History of a level

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#1002]
Mega hack will save that level into a backup folder, and if the level is updated you can view the original.

**Comment by NefariousIntent2** [comment]
An addon to #993

**Comment by MainConMan** [comment]
Unless the gd servers keep previous versions of levels, this won't be possible for most levels.

**Comment by NefariousIntent2** [comment]
> Unless the gd servers keep previous versions of levels, this won't be possible for most levels.

No like, locally save levels

**Comment by NefariousIntent2** [comment]
> Unless the gd servers keep previous versions of levels, this won't be possible for most levels.

I think? Maybe

**Comment by MainConMan** [comment]
Oh, I see

**Comment by absoIute** [comment]
Seems like a very specific thing that'd have little use when you can just copy the level instead
