### ISSUE TITLE
wave unaligns while using reverse inputs and p1 p2 input mirror

### ISSUE THREAD

**Issue by githubpub900** [absolllute/Mega-Hack-Pro-Future#1005]
![egg a](https://user-images.githubusercontent.com/73917771/186514223-66b6e59e-d524-47a6-ad39-90929cf2edca.PNG)
silent circles, whenever i hit blue orb wave breaks

**Comment by NefariousIntent2** [comment]
That is because in 2p, both players will operate independently from one another. MH Replay will not support that so it will break

**Comment by NefariousIntent2** [comment]
Looking further, replay may support that. But since p1 and p2 is known to jank up the 2p system. it probably breaks there

**Comment by absoIute** [comment]
yep just some jank GD physics going on there
