### ISSUE TITLE
Remove Annoying Particles

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#1006]
![l237dl1z](https://user-images.githubusercontent.com/107162305/186515082-c1c48b68-31ef-4e0b-a03f-5e3b31dd4a3f.png)

Remove the particles that flay across the screen like hell

**Comment by NewAlexGamer** [comment]
options, third page
![image](https://user-images.githubusercontent.com/86263500/186526649-6eccf518-ec38-4142-9041-02fc36636bc2.png)

**Comment by NefariousIntent2** [comment]
> options, third page ![image](https://user-images.githubusercontent.com/86263500/186526649-6eccf518-ec38-4142-9041-02fc36636bc2.png)

uhm...

**Comment by NefariousIntent2** [comment]
Thanks!
