### ISSUE TITLE
Capture Still Speeding Up Videos

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#1009]
I used the mega hack replay system. Didn't change FPS. Still speeding up (less noticeable)

https://user-images.githubusercontent.com/107162305/186789881-f59ceb56-ca4a-479f-98e2-3ea285af297d.mp4

)

**Comment by NewAlexGamer** [comment]
why would you create another issue for this

**Comment by NefariousIntent2** [comment]
> why would you create another issue for this

I couldn't find the issue so I thought it was closed. sorry
