### ISSUE TITLE
RNG Manipluator

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#1011]
GD has a RNG system and can you add a edit system for RNG. E.g. 0.5, .6, .7

**Comment by NefariousIntent2** [comment]
Or maybe a RNG manipulator?

**Comment by NefariousIntent2** [comment]
hmm

**Comment by absoIute** [comment]
Will add something like this for the random trigger in 2.2 but as it stands an unrandomiser is pretty useless (was in v5 and didn't get much use at all)
