### ISSUE TITLE
Comment Wait Bypass

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#1024]
Pretty straight forward, a bypass that lets you post a comment without waiting the 13 seconds after you just posted one.

**Comment by BrownieGamingX5** [comment]
Pretty interesting suggestion, but a pretty cluttered suggestion title. Could be shortened to something like "Comment Wait Bypass" or something along the lines of that.

**Comment by MainConMan** [comment]
Might not be possible. Also might not be a good idea since it could lead to comments getting spammed.

 It would be useful in some situations though, for example, if you make a typo, you don't have to wait to post it again it after deleting the original comment.

**Comment by absoIute** [comment]
Yep, not possible, there's a server-sided block
