### ISSUE TITLE
Replay doesn't respect Start Position

### ISSUE THREAD

**Issue by getkirill** [absolllute/Mega-Hack-Pro-Future#1025]
When you playing from start pos, replay ignores it and plays inputs like it's from 0%
Attaching 2 little snippets of what i mean (internal recorder)
[bug itself](https://youtu.be/B9tYJky4ek0)
[from 0%](https://youtu.be/q9mDgCxKzpE)

**Comment by MainConMan** [comment]
Duplicate of #840

**Comment by getkirill** [comment]
ohh, understandable
