### ISSUE TITLE
"Startpos Lag Bug Fix" Sometimes Doesn't Work When Botting

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#1026]
startpos lag bug fix doesn't work some attempts while botting a level. by that i mean that it works, for example, for attempt 1 to 5, but then 6 still gets the lag spike, works from 7 to 20, but 21 still gets the lag spike, and so on. still problem occurs everywhere in the level, even if those 20 attempts were all on the same click from the same checkpoint
butiti 3 is a great example as to most attempts doesn't get applied the bug fix once you get to the dual
and no this was not happening until recently, like a couple days ago

**Comment by absoIute** [comment]
Does it work better without Real Time enabled?

**Comment by NewAlexGamer** [comment]
from what i can see yes, without real time enabled it works just fine

**Comment by absoIute** [comment]
fix ready for next update
