### ISSUE TITLE
Where are configs stored?

### ISSUE THREAD

**Issue by RealFX-Code** [absolllute/Mega-Hack-Pro-Future#1027]
I recently reinstalled my PC, and copied over "%localappdata%/GeometryDash" and "C:/Program Files (x86)/Steam/Steamapps/common/Geometry Dash".

I don't have any configuration in megahack now.
Where are configurations stored?

**Comment by NewAlexGamer** [comment]
C:\Users\you\AppData\Local\Septima\options.json
