### ISSUE TITLE
The "Hitbox Trail" Sticks Out Of The End-wall 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#1030]
I swear that somebody has seen this before and has never posted it here 💀 💀 💀 

![image](https://user-images.githubusercontent.com/60493629/188257384-419dab63-5839-4951-a409-1ab453fe3d57.png)

**Comment by MainConMan** [comment]
Probably either intended or not worth fixing
