### ISSUE TITLE
"Auto Clicker" Doesn't Work With Certain Value Setups

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#1031]
beta5 released, let's start breaking stuff (foreshadowing)
if the release value is higher than the segment value, by any amount, it will not click, ever
let's presume the values are frames. i suppose it's a bug because what i understood from the hack is that the release value means how many frames it will wait before clicking again, and the segment value is how many frames it will hold the click for, which shouldn't block the autoclicker from working if the release is higher than the segment. unless they somehow work at the same time, which i wouldn't understand the need for that. the way it works, i think, is that it first does the segment part, then the release part, it's a sequence, that's what i managed to understand at least, or how a normal human would think it would work
i think a better format for the hack would be:
```
click after:
hold for:
```
this is way easier to understand in my opinion

**Comment by MainConMan** [comment]
It will be changed next beta I believe.

**Comment by absoIute** [comment]
changed in v7.1-beta6
