### ISSUE TITLE
Make "Restart Level" Shortcut Count As An Actual Death

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#1035]
i don't really know if this is a bug or an oversight, but if you die at 10 from 0, the best run will be 10%, if you use the "restart level" shortcut at 14 from 0, it will still say 10%
edit: as maincon said below me, restart level doesn't count as a death, so why not make it count as a death, this way the above problem gets solved and also what maincon said below

**Comment by MainConMan** [comment]
This is probably intended. In vanilla gd, if your best is 20%, but youre at 30% from 0, restarting wont give you the new best or orbs.

**Comment by NewAlexGamer** [comment]
oh right i forgot about that
then maybe making it count as an actual death will just solve everything instead of only best runs

**Comment by MainConMan** [comment]
Yeah i agree with that! :)

**Comment by absoIute** [comment]
Yeah, this is intended behaviour and I wouldn't really want to change it, people are used to level restarts not acting like deaths and can just cause a death and restart if they want that instead
