### ISSUE TITLE
Changing Monitor Refresh Rate in GD

### ISSUE THREAD

**Issue by FunkiestDig** [absolllute/Mega-Hack-Pro-Future#1037]
When I open GD and look to see my monitor refresh rate using the monitor OSD, GD always automatically sets it to144hz, regardless of what I change it to in the Windows display settings. I would like to change it to different values like 120hz so I can play at 360fps without the game being choppy. Do you think you could force GD to use the refresh rate I personally set my monitor to rather than defaulting to the highest refresh rate (like windowed mode)?

**Comment by MainConMan** [comment]
Borderless Fullscreen might be a temporary solution. I haven't tried it myself tho

**Comment by absoIute** [comment]
You just need to set your Hz in Windows Display Settings to 120Hz instead.
