### ISSUE TITLE
Mega hack v7 beta5 crashing game whenever opening a level

### ISSUE THREAD

**Issue by Silas123Go** [absolllute/Mega-Hack-Pro-Future#1039]
so basically ive been trying to beat map packs to get a ufo, and I got onto a level and each time i tried opening it it crashed my game. Then i tried another level and it happened again. I tried a few more levels and each time they crashed. Do you know why this is happening?

**Comment by absoIute** [comment]
send a crashlog generated in your GD folder next time this happens

**Comment by Silas123Go** [comment]
Alright dude

**Comment by Silas123Go** [comment]
Time: 2022/09/02 @ 19:03:07
Version: v7.1-beta5
Code: Unknown (0xc0020001)
Fault Address: 7506CA42
Fault Module: KERNELBASE.dll
Fault Offset: 0012CA42

Stack Walk:
KERNELBASE.dll + 0012CA42
clr.dll + 00303F2C
clr.dll + 003F1D45
clr.dll + 000106CA
GDLiveEditor.dll + 00002DD4
GDLiveEditor.dll + 00002EB6
mscoreei.dll + 00031EB8
mscoree.dll + 0000E311
mscoree.dll + 0000E353
ntdll.dll + 00072996
ntdll.dll + 0004DD42
ntdll.dll + 0005D7E5
ntdll.dll + 0005D6D5
KERNEL32.DLL + 00024113
mscoreei.dll + 00014DAB
mscoreei.dll + 00030C67
mscoree.dll + 00011C66
MSVCR120.dll + 00033F6C
MSVCR120.dll + 00033FA2
MSVCR120.dll + 0003427E
MSVCR120.dll + 000342A2
GeometryDash.exe + 00262212
KERNEL32.DLL + 0001FA29
ntdll.dll + 00067A9E
ntdll.dll + 00067A6E

Register States:
EAX: 0x10ff450
EBX: 0x1034d588
ECX: 0x1
EDX: 0
ESI: 0x1034d588
EDI: 0
ESP: 0x10ffb84
EBP: 0x10ffb8c
EIP: 0x76f47a6e
EFLAGS: 00000000001000000000001000010110

Loaded Modules (146):
002A0000: GeometryDash.exe
76EE0000: ntdll.dll
75FD0000: KERNEL32.DLL
73FB0000: aswhook.dll
74F40000: KERNELBASE.dll
753F0000: ADVAPI32.dll
75B90000: msvcrt.dll
75470000: sechost.dll
751D0000: RPCRT4.dll
76160000: SHELL32.dll
75970000: msvcp_win.dll
759F0000: ucrtbase.dll
757D0000: USER32.dll
75B10000: win32u.dll
75EC0000: GDI32.dll
75D40000: gdi32full.dll
6AAD0000: libExtensions.dll
75160000: WS2_32.dll
6A910000: libcocos2d.dll
73350000: OPENGL32.dll
754F0000: combase.dll
62AA0000: glew32.dll
6A8D0000: steam_api.dll
6A720000: fmod.dll
76940000: ole32.dll
6A6A0000: MSVCP120.dll
6A5B0000: MSVCR120.dll
6A480000: libcurl.dll
75EF0000: WLDAP32.dll
10000000: pthreadVCE2.dll
6A3F0000: sqlite3.dll
5A4C0000: zlib1.dll
6A360000: libtiff.dll
6D0B0000: XINPUT9_1_0.dll
748E0000: GLU32.dll
748B0000: WINMM.dll
740D0000: MSACM32.dll
73130000: MSVCR100.dll
74DA0000: WSOCK32.dll
6A2B0000: MSVCR90.dll
743E0000: winmmbase.dll
753B0000: IMM32.DLL
6E450000: XInput9_1_0.dll
6A100000: hackproldr.dll
75290000: CRYPT32.dll
69FB0000: gameoverlayrenderer.dll
760C0000: OLEAUT32.dll
75C50000: PSAPI.DLL
74E00000: shcore.dll
737D0000: windows.storage.dll
737A0000: Wldp.dll
75B40000: SHLWAPI.dll
75E20000: cfgmgr32.dll
75390000: bcrypt.dll
74C00000: IPHLPAPI.DLL
74950000: VERSION.dll
72890000: MSWSOCK.dll
73F50000: CRYPTBASE.DLL
75E60000: bcryptPrimitives.dll
66AD0000: hackpro.dll
74E90000: COMDLG32.dll
728F0000: dbghelp.dll
74D50000: dwmapi.dll
69AF0000: discord_game_sdk.dll
6E8C0000: COMCTL32.dll
69970000: MFPlat.DLL
69F20000: MF.dll
698B0000: MFReadWrite.dll
744E0000: dxgi.dll
70C20000: d3d11.dll
69F10000: ktmw32.dll
66770000: MFCORE.DLL
69E00000: powrprof.dll
74890000: ksuser.dll
74870000: kernel.appcore.dll
695B0000: mfperfhelper.dll
69E50000: RTWorkQ.DLL
73FD0000: UMPDC.dll
73E00000: dbgcore.DLL
694A0000: CSERHelper.dll
748A0000: XInput1_4.dll
72200000: DEVOBJ.dll
73260000: inputhost.dll
74660000: CoreMessaging.dll
71C50000: PROPSYS.dll
039B0000: wintypes.dll
74130000: CoreUIComponents.dll
72140000: ntmarta.dll
73580000: uxtheme.dll
75C60000: MSCTF.dll
75F50000: clbcatq.dll
65DC0000: ig8icd32.dll
65520000: igdusc32.dll
74D10000: WTSAPI32.dll
72590000: dxcore.dll
74700000: textinputframework.dll
72230000: Oleacc.dll
72640000: DNSAPI.dll
753E0000: NSI.dll
73F60000: rasadhlp.dll
725E0000: fwpuclnt.dll
72120000: profapi.dll
69F00000: AltTabFix-v1.0.dll
69EF0000: minhook.x32.dll
69E80000: MSVCP140.dll
6E430000: VCRUNTIME140.dll
687B0000: BetterEdit-v4.0.5-min.dll
69170000: gdiplus.dll
69480000: GDLiveEditor.dll
69420000: mscoree.dll
69390000: mscoreei.dll
64CD0000: clr.dll
69370000: VCRUNTIME140_CLR0400.dll
682B0000: ucrtbase_clr0400.dll
638C0000: mscorlib.ni.dll
68720000: clrjit.dll
68220000: GDShare-v0.3.4.dll
68210000: GPMods.dll
681F0000: GroupIDFilter.dll
681C0000: IconSave.dll
681A0000: menu-shaders.dll
68130000: SaiModPack.dll
68100000: SceneSwitcher-v1.1.dll
680E0000: ScrollAnyInput-v1.1.dll
680C0000: song-search.dll
68090000: textureldr.dll
638A0000: VolumeControl.dll
63880000: GDClipboardFix.dll
68080000: every-key-jumps.dll
63870000: fps-multiplier.dll
63860000: invisible-dual-bugfix.dll
63850000: rgb-color-input.dll
63840000: run-info.dll
63830000: SettingsInLayer.dll
63820000: sum-attempts.dll
72170000: MMDevApi.dll
70E60000: AUDIOSES.DLL
63720000: Windows.UI.dll
636A0000: WindowManagementAPI.dll
68360000: twinapi.appcore.dll
73FE0000: wdmaud.drv
745B0000: AVRT.dll
743D0000: msacm32.drv
740C0000: midimap.dll
62850000: resourcepolicyclient.dll
71BA0000: TextShaping.dll

System:
CPU:       Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
System RAM: 1,204,760 KB
Available RAM: 2,097,024 KB
GPU: Intel(R) HD Graphics

END OF LOG
Im on beta6 rn so idk why it still says beta5

**Comment by NewAlexGamer** [comment]
> Im on beta6 rn so idk why it still says beta5

because the crash happened on beta 5

**Comment by Silas123Go** [comment]
> > Im on beta6 rn so idk why it still says beta5
> 
> because the crash happened on beta 5

wait i sent the wrong log, gimme a sec

**Comment by Silas123Go** [comment]
[23/09/2022 20:06:00]
Oh no! an exception has occurred. anyways heres some info
Module Name: GeometryDash.exe
Exception Code: 0xe06d7363 (idk lol)
Exception Flags: 1
Exception Address: 7595CC12 (KERNELBASE.dll + 0x12cc12)
Number Parameters: 3
Stack Trace:
 - C:\WINDOWS\System32\KERNELBASE.dll + 0x12cc12
 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll + 0x75b6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\GeometryCache.dll + 0x331b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\GeometryCache.dll + 0x3d07
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\GeometryCache.dll + 0x292b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xebb74
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xd379b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xd31d6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\GDShare-v0.3.4.dll + 0xfc10
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\BetterEdit-v4.0.5.dll + 0x3ff65
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x15a005
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x4eba0
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xabe83
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xaaf1d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xf5919
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xbb37c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xc4046
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\extensions\BetterEdit-v4.0.5.dll + 0xa3f52
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xc406e
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x111b29
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x113679
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\hackpro.dll + 0x1300e3
 - C:\WINDOWS\System32\USER32.dll + 0x40bcb
 - C:\WINDOWS\System32\USER32.dll + 0x37b8a
 - C:\WINDOWS\System32\USER32.dll + 0x37267
 - C:\WINDOWS\System32\USER32.dll + 0x3540b
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 0x477bf
 - C:\WINDOWS\System32\USER32.dll + 0x40bcb
 - C:\WINDOWS\System32\USER32.dll + 0x37b8a
 - C:\WINDOWS\System32\USER32.dll + 0x358fa
 - C:\WINDOWS\System32\USER32.dll + 0x356c0
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 0x80060
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x1122d2
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xc190b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x261175
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 0x1fa29
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67b5e
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67b2e

**Comment by Silas123Go** [comment]
new crash logs from mega hack itself arent being created so I used one from the crash log extension, hopefully this works.

**Comment by absoIute** [comment]
looks like an issue with GeometryCache
