### ISSUE TITLE
Option to force Cheat Indicator to be green

### ISSUE THREAD

**Issue by getkirill** [absolllute/Mega-Hack-Pro-Future#1041]
Will help script kiddies to pass their totally (not) cool replay as legit by always making cheat indicator green. Might defeat the whole purpose of it.  
(and yeah i know that you can tell ppl that you don't have indicate no cheats turned on and then turn off cheat indicator completely with hacks, but green indicator is much more believable)

**Comment by NewAlexGamer** [comment]
yes it would defeat the purpose of the cheat indicator, it wouldn't even make sense to keep it as a feature if people can just fake it

**Comment by getkirill** [comment]
yeah no i don't want to ruin it lol
