### ISSUE TITLE
Longer Editor Extension

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#1046]
Is it possible to make the editor extend infinitely?

**Comment by NewAlexGamer** [comment]
if you mean extending the floor and roof of the editor it probably is, but it would probably work only locally
also you have this (honestly i still don't know what it does to this day but it has the same name as the issue)
![image](https://user-images.githubusercontent.com/86263500/188563810-09408753-52d5-4c86-bea6-5a363395e4a7.png)

**Comment by FnigePython** [comment]
> (honestly i still don't know what it does to this day but it has the same name as the issue)

Iirc that makes the length of the editor longer, letting you make longer levels

**Comment by Unspeakable-Boy** [comment]
Sorry for all the confusion, the title is changed. It basically makes the editor longer than by a factor of 128.

**Comment by Unspeakable-Boy** [comment]
> if you mean extending the floor and roof of the editor it probably is, but it would probably work only locally also you have this (honestly i still don't know what it does to this day but it has the same name as the issue) ![image](https://user-images.githubusercontent.com/86263500/188563810-09408753-52d5-4c86-bea6-5a363395e4a7.png)

Editor extension makes the level length longer, but not infinitely longer. Thats what I'm asking. Sorry for all the confusion.

**Comment by absoIute** [comment]
For more precision go to Variables -> Creator -> Editor Length
