### ISSUE TITLE
Add interpolation (and possibly a new renderer)

### ISSUE THREAD

**Issue by CoderQCFromScraatch** [absolllute/Mega-Hack-Pro-Future#1049]
I don't care if this requires reworking the entire renderer, I want to interpolate my game so it looks smooth no matter the FPS.

**Comment by BrownieGamingX5** [comment]
Pretty interesting idea. But how would be implemented into the internal recorder though. My computer runs pretty well with my current settings: 
![image](https://user-images.githubusercontent.com/60493629/189287582-725d7b14-9f61-4626-8d8d-00eeca3175d9.png)


Yeah, every time I start recording by using the internal recorder to record a 4K showcase, it literally looks like it is rendering the entire macro in 0.5x speed, which is pretty fast.

**Comment by CoderQCFromScraatch** [comment]
I wasn't talking about the internal recorder, I was talking about the game's OpenGL renderer. It doesn't matter with the internal renderer as you can set the exported FPS. What matters is the perceived FPS, ie. It looks like 240 FPS but the game is actually running 60 fps due to the interpolation. You don't need interpolation to have a frame rate option because it won't matter if it goes past the user's refresh rate as no difference will be perceived by the user.

**Comment by x8c8r** [comment]
You DO understand that rewriting THE ENTIRE renderer is not worth 4$ you gave Absolute when you bought MH? It's too much effort to even bother, and it will probably take so long, so you won't even care when it's done.

**Comment by absoIute** [comment]
Would require too much work for a whole lot of not much use

**Comment by CoderQCFromScraatch** [comment]
I do understand, just wanted to pitch that idea out there.
