### ISSUE TITLE
View Likes AND Dislike On Level, Comments, Profile Posts, etc.

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#1055]
Instead of adding up all the likes and dislikes on levels, comments, profile posts, etc, you can see the total amount of likes next to the total amount of dislikes, and below it is the two combined.

**Comment by MainConMan** [comment]
Probably not possible

**Comment by absoIute** [comment]
Not possible sadly, server only reports the total
