### ISSUE TITLE
Sometimes Confirm Exit Being Small and Freeze The Game

### ISSUE THREAD

**Issue by AxoCode** [absolllute/Mega-Hack-Pro-Future#1057]
Version : v7.1-beta6

Expected Behaviour : When you turn on "Confirm Exit", if you press ESC, or the menu button. It will show a confirmation popup.

But sometimes, the popup is too small.
If you click the "OK" button. It will freeze the game (no not responding), but not the megahack.
If you click cancel or press esc. The bug fixed.

I still dont know how to replicate the issue. But sometimes happened.

Here is a video that I accidentally click to OK button in the small popup

https://user-images.githubusercontent.com/57800056/190091080-32c24904-e7ad-4b35-83cc-6ca055a28390.mp4

**Comment by NewAlexGamer** [comment]
This happens if you are using frame stepper since it goes frame by frame not only while playing but also in the pause menu and stuff

**Comment by AxoCode** [comment]
Yeah, I just realised now. lmao, my mistake.

**Comment by AxoCode** [comment]
sometimes no?
https://user-images.githubusercontent.com/57800056/190102114-23f664be-e556-4b8f-8128-bd3d3d0a0cca.mp4

**Comment by NewAlexGamer** [comment]
apparently if you use the backwards/forwards stepping before clicking on the leave button it fixes the popup going 1 frame at a time
