### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by MegahackILoveYou** [absolllute/Mega-Hack-Pro-Future#1064]
Hey add please custom backround and all achievments in steam, this is so cool. But can you add custom backround in menu with gif?

**Comment by MegahackILoveYou** [comment]
> For the animated background you can use the menu shader extension and custom backgrounds as simple images can be done with texture packs I don't know about steam achievements, I don't think that's a possible thing. Alternatively you can cheat your way through the achievements

Sorry how i can use animate background? im need it, okay im not need achievmnets but im need animate background, sorry, im not english, i dont know how translate your words.

**Comment by MegahackILoveYou** [comment]
> For the animated background you can use the menu shader extension and custom backgrounds as simple images can be done with texture packs I don't know about steam achievements, I don't think that's a possible thing. Alternatively you can cheat your way through the achievements

Sorry how i can use animate background? im need it, okay im not need achievmnets but im need animate background, sorry, im not english, i dont know how translate your words.

**Comment by MegahackILoveYou** [comment]
> download the extension "menu shaders" from here https://matcool.github.io/mods by default it already has an animation but you can get 2 more from those tweets https://twitter.com/mateus44_/status/1412108556921344006?s=20 if you want something truly customized for example something else or something made by you that's all coding the actual animation, the format of those shaders are actually used and you can find some of them online

OMG YOU RE BEST THANKS!

**Comment by MegahackILoveYou** [comment]
> download the extension "menu shaders" from here https://matcool.github.io/mods by default it already has an animation but you can get 2 more from those tweets https://twitter.com/mateus44_/status/1412108556921344006?s=20 if you want something truly customized for example something else or something made by you that's all coding the actual animation, the format of those shaders are actually used and you can find some of them online 

OMG THANKS! Im cant open twitter but default animation is so cool!

**Comment by MegahackILoveYou** [comment]
> download the extension "menu shaders" from here https://matcool.github.io/mods by default it already has an animation but you can get 2 more from those tweets https://twitter.com/mateus44_/status/1412108556921344006?s=20 if you want something truly customized for example something else or something made by you that's all coding the actual animation, the format of those shaders are actually used and you can find some of them online

How to change background? I have .fsh files

**Comment by NewAlexGamer** [comment]
That I forgot, and it doesn't seem to anywhere in the link I sent you. If I remember correctly either a folder made for shades or it has to have a specific name, but I'm not sure. You can enter the gd modding discord server and ask there if you want

**Comment by MegahackILoveYou** [comment]
> That I forgot, and it doesn't seem to anywhere in the link I sent you. If I remember correctly either a folder made for shades or it has to have a specific name, but I'm not sure. You can enter the gd modding discord server and ask there if you want

Thanks.
