### ISSUE TITLE
Integrated Clickbot with MHv7.1 Replay

### ISSUE THREAD

**Issue by FunkiestDig** [absolllute/Mega-Hack-Pro-Future#1065]
There would be a new button under the "Macro" tab called "Clickbot" which you could activate and would have its own folder in the GD directory called "Clicks" in which you could add any click sounds and have clicks similar to what you see Neiro and fnm04 doing in their showcases. (Basically just Abot/Cbot (or any clickbot), but compatible and integrated with MHv7.1

**Comment by MainConMan** [comment]
Absolute has already said he doesn't want to add this.
