### ISSUE TITLE
Accurate Percent On New Best

### ISSUE THREAD

**Issue by SharkyMantisGD** [absolllute/Mega-Hack-Pro-Future#1066]
On an XL level, you can be on a single % for a while, and if you die in 2 different spots on the same %, it won’t count. But with the accurate percent on, it can count that too. Ex:                

                  New Best!         a minute later:          New Best!
                  54.9563%                                   54.9893%

It could also be shown when your outside of the level, or in the comments.

**Comment by NewAlexGamer** [comment]
you can enable the accurate percentage in the best run settings, it will use the same decimals as the accurate percentage. honestly tho having them as 2 separate options instead of best run using the same as accurate percentage wouldn't be bad
comments would work only locally so not much use for that

**Comment by MegahackILoveYou** [comment]
> you can enable the accurate percentage in the best run settings, it will use the same decimals as the accurate percentage. honestly tho having them as 2 separate options instead of best run using the same as accurate percentage wouldn't be bad comments would work only locally so not much use for that

Yes, but maybe accurate percentage in  progress bar in menu? this is so cool

**Comment by totallyphysicallypossible** [comment]
I don't think the game keeps track of progress with decimals

**Comment by absoIute** [comment]
The game doesn't track % in decimal format, won't be changing that sorry
