### ISSUE TITLE
Show Block Position (x and y axis) In Editor, Plus, Type the Position You Want to Place a Block.

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#1068]
Shows you the x and y position on the grid in the editor, plus type the position you want a block/item to be at. The uses for it are kinda small, but it would be funny how people use it, I could think of a few.

**Comment by totallyphysicallypossible** [comment]
BetterEdit's Experimental Features already has a context menu where you can change the x and y positions

**Comment by MainConMan** [comment]
That, and it already exists in the variables tab!
