### ISSUE TITLE
The "Wave Trail On Death" Feature Still Keeps The Wave Trail After Entering A Game-mode Portal

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#1073]
For a while, I actually noticed this bug, but for some reason, I never decided to report it here.

![image](https://user-images.githubusercontent.com/60493629/191665333-e8d7ed14-d2b0-4697-a38b-7fc266927485.png)

![image](https://user-images.githubusercontent.com/60493629/191665299-6ce6c3f1-cec5-48dc-90f5-afa0e281b719.png)

**Comment by Unspeakable-Boy** [comment]
Fix for that would be good!

**Comment by MainConMan** [comment]
i told absolute about this on like day 5 of alpha and he never fixed it 💀

**Comment by NewAlexGamer** [comment]
i think this should stay actually, it still helps you figure out how close to things you were after playing the part

**Comment by MainConMan** [comment]
Could be a sub-menu option

**Comment by absoIute** [comment]
fixed a while back
