### ISSUE TITLE
Having V-Sync On/Off Doesn't Allow For "Lock Delta" To Be Used

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#1075]
Pretty self explanatory. 

I don't know if this has occurred with other people, but from what I have tested, you cannot enable "Lock Delta" with V-Sync on or  off.

**Comment by BrownieGamingX5** [comment]
Yes, I already know that. But can it also be used by having V-Sync being enabled alone instead of using the FPS or TPS bypass to be used.

**Comment by absoIute** [comment]
behaviour changed now
