### ISSUE TITLE
Error 1114 

### ISSUE THREAD

**Issue by SimonGFL** [absolllute/Mega-Hack-Pro-Future#1078]
If i try to inject a mit in mh v7 it says error 1114 I dont know why

**Comment by CoderQCFromScraatch** [comment]
We should have documentation for these errors.

**Comment by Brittank88** [comment]
> We should have documentation for these errors.

These may not be MH errors as much as underlying error codes, which may still not mean much of anything to an end-user. That's up to @absoIute to explain better though.

**Comment by absoIute** [comment]
it's a Microsoft error code meaning the DLL you're injecting failed to initialise, can definitely stringify them in a future update.
it's an issue with the DLL you're loading specifically, not Mega Hack
