### ISSUE TITLE
Indicator for having no plugins/dlls apart from the main MH injected. 

### ISSUE THREAD

**Issue by x8c8r** [absolllute/Mega-Hack-Pro-Future#1083]
I think something like this could prove a person even more legit. Since most if not all of bots rely on having to be injected in the game itself. And if there will be an indicator to prove that there is nothing else except for Mega Hack itself and no hacks turned on, then it can really help.

**Comment by MainConMan** [comment]
Some extensions are perfectly fine though, like icon save for example, it doesn't even effect you in the level.

**Comment by x8c8r** [comment]
> Some extensions are perfectly fine though, like icon save for example, it doesn't even effect you in the level.

yea, that is true, but I still think this should be added for people who needed, tho I am not sure if it's easy enough to implement

**Comment by sinc0s** [comment]
Would be pretty simple to implement but not very helpful since almost everyone uses extensions anyways

**Comment by x8c8r** [comment]
> Would be pretty simple to implement but not very helpful since almost everyone uses extensions anyways

ehh, its not really supposed to be used for everyone, but more of a last resort

**Comment by absoIute** [comment]
an indicator like this would be easy to bypass, there's plenty of known ways to inject DLLs undetected so having it at all wouldn't suffice as a legitness indicator
