### ISSUE TITLE
Icon effects bug

### ISSUE THREAD

**Issue by MegahackILoveYou** [absolllute/Mega-Hack-Pro-Future#1084]
when im set all to fade, this is blinking, for example im use black and white fade colors and it blinks sometime

**Comment by MainConMan** [comment]
Send a video and show your enabled hacks!

**Comment by MegahackILoveYou** [comment]
> 
 im cant send a video, my computer is so bad but i will try

**Comment by MegahackILoveYou** [comment]
https://user-images.githubusercontent.com/113890737/192556819-aaf9f874-fbde-4528-951a-d801d667e968.mp4

**Comment by MainConMan** [comment]
Turn on No Force Player Glow in cosmetic tab.

**Comment by MegahackILoveYou** [comment]
It work, thanks.
