### ISSUE TITLE
Replay And Record Don't Visually Turn On Lock Delta In Menu

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#1086]
while classic mode for speedhack gets turned on and blacked out, lock delta still gets turned on, but it's not visually indicated in the menu
![image](https://user-images.githubusercontent.com/86263500/192642198-43156b58-b30e-4fd7-bcd3-e5737190b824.png)
also flicker fix is always blacked out for some reason idk why

**Comment by sinc0s** [comment]
I'm pretty sure this is an issue with the new beta update, hopefully it's sorted soon.

**Comment by MainConMan** [comment]
Flicker Fix is probably blacked out because you don't have the hardware that causes the flickering bug... Let us know if I'm wrong tho

**Comment by absoIute** [comment]
fixed in uh some beta update
