### ISSUE TITLE
Whitespace bug

### ISSUE THREAD

**Issue by MegahackILoveYou** [absolllute/Mega-Hack-Pro-Future#1089]
if im playing in whitespace and touch to he 1 times, cps counter show 2 clicks, but this is only one click

**Comment by Brittank88** [comment]
Can you elaborate? I have no idea what "touch to he 1 times" means.

**Comment by MegahackILoveYou** [comment]
The fact that I press the space bar 1 time, but the counter shows 2

**Comment by MainConMan** [comment]
Send a screenshot of your enabled hacks!

**Comment by MegahackILoveYou** [comment]
> Send a screenshot of your enabled hacks!

how, i cant

**Comment by Brittank88** [comment]
> how, i cant

Should just be able to use printscr lol

**Comment by MegahackILoveYou** [comment]
> > how, i cant
> 
> Should just be able to use printscr lol

not working

**Comment by MegahackILoveYou** [comment]
![image](https://user-images.githubusercontent.com/113890737/194079609-35a54a7d-234e-4194-b73d-b8471b61d425.png)

**Comment by MegahackILoveYou** [comment]
![image](https://user-images.githubusercontent.com/113890737/194079806-7f7e1c10-5e06-4cb7-8625-9167de791b74.png)

**Comment by MainConMan** [comment]
its because you have space bar for P1 jump and p2 jump in shortcuts tab

**Comment by Brittank88** [comment]
Good pickup @MainConMan

**Comment by NewAlexGamer** [comment]
wait you're telling me now those keybinds actually work? because i've tried that yesterday yet i couldn't have neither the double click nor the keybinds to actually work
i set them to j and k if you're wondering

**Comment by MainConMan** [comment]
> Good pickup @MainConMan 

ty :)

**Comment by MainConMan** [comment]
> wait you're telling me now those keybinds actually work? because i've tried that yesterday yet i couldn't have neither the double click nor the keybinds to actually work
> i set them to j and k if you're wondering

weird, theyve always worked for me...

**Comment by NewAlexGamer** [comment]
wait they've never worked for me

**Comment by MainConMan** [comment]
you should probably make a new issue for that, unless theyre working now

**Comment by NewAlexGamer** [comment]
i was about to edit that comment before you read it so i wouldn't have sent another one but i guess i'm still doing it
i realized after posting the comment that i've reported that already in the past and it was apparently a conflict with betteredit

**Comment by MainConMan** [comment]
ohh
