### ISSUE TITLE
No Mirror Affects Vanilla Accuracy Macros

### ISSUE THREAD

**Issue by barraIhsan** [absolllute/Mega-Hack-Pro-Future#1091]
(bad quality, cause github's 10 MB limit)

https://user-images.githubusercontent.com/57800056/193405259-5ef25a1f-5c4f-428b-a0fe-9f637808e5c3.mp4

(With No Mirror)

https://user-images.githubusercontent.com/57800056/193405264-f4a792fd-df5a-4815-b2f7-b38c0f8f0c7c.mp4

(Without No Mirror)

Mega Hack Replay File : [Silent Clubstep.mhr.gz](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9689960/Silent.Clubstep.mhr.gz)
As you can see from that video.
When turning on No Mirror (Vanillla Accuracy), it will complete the level.
But when you turn off No Mirror, it will die at 18% (Actually it worse than that, you can see if you turn on NoClip)

**Comment by absoIute** [comment]
mirror portals are known to cause misalignments, not a bug
