### ISSUE TITLE
High FPS Lag

### ISSUE THREAD

**Issue by NothingIsScary** [absolllute/Mega-Hack-Pro-Future#1096]
Playing on high FPS with dense levels causes smooth fix style slowdown. even if all settings related to smooth fix are off. this only happens when you install v7 Beta. if you dont do the beta. the lag doesnt happen.

**Comment by totallyphysicallypossible** [comment]
Lock Delta, fsr it can get enabled even when it appears disabled from what i experienced yesterday

**Comment by NothingIsScary** [comment]
Yup. the new megahack update fixed it! thanks!
