### ISSUE TITLE
Enable "TPS Bypass" Instead Of "FPS Bypass" When Replaying

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#1098]
when you replay a level it always sets your fps to the amount it was recorded in. having an option to make it enable the tps instead would be useful, since i play on a laptop and usually replay levels while it's not set on the highest performance, i always have half of those fps and it's not that great to look at so i set the tps instead every time
clearly this can't be done when the fps in replay is lower than your current, but the above situation can be valid

**Comment by 1nfernotm** [comment]
pretty sure it already does, if you have an fps set already

**Comment by absoIute** [comment]
it works like that already, the way vsync works with it also changed!
