### ISSUE TITLE
question

### ISSUE THREAD

**Issue by MegahackILoveYou** [absolllute/Mega-Hack-Pro-Future#1104]
When 2.2 exists. will I need to buy again megahack for the new version?

**Comment by SharkyMantisGD** [comment]
> When 2.2 exists. will I need to buy again megahack for the new version?

Good question, I'd like to know too.

**Comment by sinc0s** [comment]
No

**Comment by MainConMan** [comment]
Once you buy megahack, youll never have to pay for updates

**Comment by MegahackILoveYou** [comment]
> Once you buy megahack, youll never have to pay for updates

ok thank
