### ISSUE TITLE
Green Dot to Show Who's Got the Game Open

### ISSUE THREAD

**Issue by SharkyMantisGD** [absolllute/Mega-Hack-Pro-Future#1105]
When you look at a user's profile, on a side of their name, you can see a green dot that show's they have Geometry Dash open. I don't know if this might be invading people's privacy of some sort, but it would be cool to see.

**Comment by MainConMan** [comment]
If it were to be implemented, it would most likely only work for people who also use megahack.

**Comment by Theboiboi8** [comment]
I mean realistically, if normal people want this they should just buy MH. Plus, the purpose of MH Pro is basically just to flex on your friends cause they're poor, and you are not and can do cool things that they cant

**Comment by SharkyMantisGD** [comment]
> I mean realistically, if normal people want this they should just buy MH. Plus, the purpose of MH Pro is basically just to flex on your friends cause they're poor, and you are not and can do cool things that they cant

Exactly, and showing who’s got the game open is something cool the ‘poor’ people can’t do. It’s not that big of a deal, though, because as MainConMan said, you might only see the dot on peoples profiles if they bought Mega Hack. But thanks for the feedback!

**Comment by absoIute** [comment]
Steam does this! Don't wanna add things like that that'd require more server stuff than needed
