### ISSUE TITLE
Recording Macros Bug

### ISSUE THREAD

**Issue by NothingIsScary** [absolllute/Mega-Hack-Pro-Future#1113]
Basically from what I have discovered in my testing. if you enable No Mirror. Bot a level with mirrors. and then play the Macro with No Mirror turned off. The macro breaks.

Its hard to describe so ill include one of the bugged macros. It was recorded with No Mirror turned on. the bot works with it turned on. but if you turn it off it doesn't work.

Level Botted : 4125776
[Silent Clubstep.zip](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9885003/Silent.Clubstep.zip)

**Comment by absoIute** [comment]
expected behaviour, mirror portals affect physics
