### ISSUE TITLE
Bug with menu buttons+icons being shown on top of each other

### ISSUE THREAD

**Issue by WowDisco** [absolllute/Mega-Hack-Pro-Future#1120]
![IconKitBug](https://user-images.githubusercontent.com/117533765/200132000-f9864a13-3d91-4e32-add2-3e0586deaf73.png)
![MainMenuBug](https://user-images.githubusercontent.com/117533765/200132003-073daa2a-8b53-495c-bee4-6b8e9b6c88a5.png)
![IconBug](https://user-images.githubusercontent.com/117533765/200132004-d68d5d3d-ad69-41dd-b7e4-996616c98690.png)
![MainLevelsBug](https://user-images.githubusercontent.com/117533765/200132006-904c89e5-c8d9-4cc0-bd6d-2d514c00815c.png)

I know this isn't a bug with my copy of GD because when I uninstall MegaHack v7.1, it goes away.
It's possible that this is a setting that I have enabled somewhere, but I can't find that option.

**Comment by BrownieGamingX5** [comment]
The reason why is probably you accidently have "Force Visibility" enabled in the "Universal" tab as shown here: ![image](https://user-images.githubusercontent.com/60493629/200185004-f164fb2a-6320-4830-b946-f20d2a11e623.png)

**Comment by MainConMan** [comment]
^ if this is true, it isnt a bug, but if you dont please let us know!
