### ISSUE TITLE
Add clicks to mh v7.1 macros

### ISSUE THREAD

**Issue by Hyyped** [absolllute/Mega-Hack-Pro-Future#1127]
Title says it all

**Comment by NewAlexGamer** [comment]
what? you mean actually clicking, displaying the clicks, or being able to edit them? because you can do all 3 of them

**Comment by Hyyped** [comment]
I mean a clickbot implemented into the macro

**Comment by MainConMan** [comment]
Absolute has said in the past he doesnt want to add a clickbot.
