### ISSUE TITLE
A visual fix for portals colored using a color ID

### ISSUE THREAD

**Issue by Spidapida** [absolllute/Mega-Hack-Pro-Future#1133]
Right now, the game doesn't fully color the portals if you do it by pasting what color ID a portal should use. The only workaround for the vanilla game is by coloring them using pulse trigger.
![Left - A portal colored by copying values on one object then pasting it to the portal --- Right - A portal colored using a pulse trigger](https://user-images.githubusercontent.com/115771797/205447225-4a9deba0-5dc3-4b57-879f-4e9f21b24373.png)

**Comment by absoIute** [comment]
would cause an inconsistency when creating levels for anyone else not using this option, use pulse triggers so it looks good for everyone!

**Comment by Brittank88** [comment]
Agreed - there's already a correct way to do it, not much point in introducing inconsistency.
