### ISSUE TITLE
Gradient for icon effects only displays the topmost list color you inputted

### ISSUE THREAD

**Issue by Spidapida** [absolllute/Mega-Hack-Pro-Future#1139]
![image](https://user-images.githubusercontent.com/115771797/208108023-1b22ae7b-ef6e-4bdf-bebc-ee210494e528.png)

Also, while at it, if there's a way to rearrange the palettes without deleting and re adding colors, that would be nice.

**Comment by absoIute** [comment]
it cycles between the colours, your cycle speed is just hella low
