### ISSUE TITLE
Son bought pro but getting DLL errors and tab does nothing

### ISSUE THREAD

**Issue by jorvis** [absolllute/Mega-Hack-Pro-Future#1157]
I bought the latest version for him and watched him install it.  It writes all the files but when he opens the geometry dash executable two missing DLL errors appear, then geometry dash opens but the tab character does nothing.

I followed the Getting Help link provided and installed both DLL packages suggested, restarted the machine, and the same issue persists.  Help?

**Comment by CoderQCFromScraatch** [comment]
Install the [Visual Studio Runtime 2015 (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=53840), and that might fix it.

**Comment by jorvis** [comment]
Thanks for the response, but that didn't work.  It was one of the things we installed already to try to make it work.  I typically work in the Linux world - is there a way to see which DLLs it's expecting?

**Comment by NewAlexGamer** [comment]
just making sure, try following this thread (#36 ) and tell us if it solved or that's what you originally did. in case nothing changed i'm sorry but here's where my linux tips stop

**Comment by MainConMan** [comment]
It may also be an antivirus issue but not sure

**Comment by jorvis** [comment]
The author responded to him directly and said that it had to be the version of Geometry Dash that was installed via Steam rather than the stand-alone to work.  Things are working now.

**Comment by Brittank88** [comment]
This was a wholesome issue I hope your son enjoys the game + MH 😃
