### ISSUE TITLE
I have a problem with the MHV6

### ISSUE THREAD

**Issue by ElParaguasXD** [absolllute/Mega-Hack-Pro-Future#1160]
I have a problem when opening the game with MHV6/V7 installed, when I uninstall MHV6/V7, the game opens but for 10 seconds and then crashes 

In english: "Cannot find procedure entry point ?getTag@CCHttpReques@extension@cocos2d@@QAEPBDXZ in dynamic link library"

how can I solve it?

![problem](https://user-images.githubusercontent.com/98687237/216655807-7c1ad67a-b6c9-4c38-9aba-e60b78b962f4.png)

**Comment by Brittank88** [comment]
Oh wait I just noticed that this is not the Steam version of GD. You must use the Steam version of GD for Mega Hack to work on it.
