### ISSUE TITLE
My Mega Hack V7.1 doesn't let me play levels

### ISSUE THREAD

**Issue by average-genshin-player** [absolllute/Mega-Hack-Pro-Future#1161]
So I purchased MegaHack V7.1 from the Absolute store and used it for a few months. Just yesterday, I randomly started being unable to play levels. Whenever I open a level, the song plays but the icon doesn't appear and the camera doesn't move. As soon as I uninstall MegaHack, levels play like usual. I do use a legitimate copy of Geometry Dash. I have looked all over the internet, trying the typical solutions like reinstalling (both the game and just the software), restarting (did it like twice), uninstall, restart, reinstalling, compatibility mode, running as admin, excluding `hackpro.dll` and `hackproldr.dll` on my antivirus, clearing extensions and all of them combined, but it just didn't work. I can't find anything on the internet which describes a situation like mine. Please help.

**Comment by average-genshin-player** [comment]
I'm stupid, I had frame stepper on the whole time. Why am I so dumb.

**Comment by MainConMan** [comment]
Ive done this like 3 times lol, happens to the best of us
