### ISSUE TITLE
Automatically Enable Safe Mode on Illegal Mods

### ISSUE THREAD

**Issue by uhmily** [absolllute/Mega-Hack-Pro-Future#1195]
Adding a toggle-able option to automatically enable safe mode when any illegal mods (mods that would turn the hack detector red) are present would prevent so many accidental hacked completions.

**Comment by NewAlexGamer** [comment]
![image](https://github.com/absolllute/Mega-Hack-Pro-Future/assets/86263500/ed5d571f-8a3c-444a-bedf-9d02c79b4f29)

**Comment by Brittank88** [comment]
Also hi!!
