### ISSUE TITLE
Auto Music Sync desyncs while there's no visual lag

### ISSUE THREAD

**Issue by xparadoxical** [absolllute/Mega-Hack-Pro-Future#1236]
I don't recall anything like that ever happening before. v7.1.1-GM2.
Play levelid 91577619 and notice how at about 3.2-3.4% Auto Music Sync starts constantly getting triggered when you're not lagging (because there are barely any objects in this level). It desyncs the song by delaying it. You can set the treshold to the maximum (250ms) to make the effect drastically noticable.

I Level Edit'd the level to place a vertical line at the X position of the 4x speed portal placed at the very top of the level area. And indeed, looks like Auto Music Sync does not like that portal. Doesn't look like actually going through the portal (by using the invisible blue orb) matters.

Fun thing: with Auto Music Sync enabled with a low treshold, like the default 40ms, and with Speedhack Audio disabled, using Speedhack at 1.8x speed past the 3.2-3.4% point nullifies Auto Music Sync's effects really well and makes the song almost perfectly what it should be without Auto Music Sync being bugged.

Tried Deadlocked and it's fine there 🤷‍♂️

**Comment by NewAlexGamer** [comment]
that's how auto music sync is supposed to work, if you miss any speed portal it compensated for the speed your currently at and slows/speeds up the song. same thing if you try and miss the wave speed portal in deadlock at the beginning, the song will slow down to compensate for the fact you're slower than the intended speed

**Comment by xparadoxical** [comment]
TIL that's how it works. Unchecking the portal and going through it makes AMS speed up the song.
