### ISSUE TITLE
Separate dual icons + best run addition

### ISSUE THREAD

**Issue by Wolfflash** [absolllute/Mega-Hack-Pro-Future#1247]
Separate dual icons is pretty self-explanatory You would be able to change player2's icon independently from P1 this could just be an arrow on the right side of the icon selection screen with an indicator showing if your editing player1 or player2.

Best runs could have an option to Show "cheated" runs example when using speed hack it would show red and still show the best run this would be an option you could enable.

**Comment by NewAlexGamer** [comment]
separate dual icons is already a thing, there's an extension for it

**Comment by Wolfflash** [comment]
> 

can you link it ive never found one

**Comment by Wolfflash** [comment]
> separate dual icons is already a thing, there's an extension for it

can you link it please?

**Comment by NewAlexGamer** [comment]
https://github.com/Alphatism/SeparateDualIcons/releases/latest

**Comment by Wolfflash** [comment]
ty
