### ISSUE TITLE
[Geode] Crashing when I complete a quest while using mhv7

### ISSUE THREAD

**Issue by LukaTV939** [absolllute/Mega-Hack-Pro-Future#1253]
As the title says my game crashes when I complete a quest while using mhv7 on Geode
[Crash Logs](https://gist.github.com/LukaTV939/9ede4b7aa5479a68f8610e3304a738ca)
[Example (Streamable)](https://streamable.com/9r65gp)

**Comment by LukaTV939** [comment]
> When you install `Geode`, it clearly says: ![image](https://user-images.githubusercontent.com/101340400/272362219-f4f27a43-a3ba-41d1-b911-078eba48123d.png) So geode is quite incompatible with MH, so absolute can't fix it right now and will not do it

I'm sorry but this exists:
![image](https://github.com/absolllute/Mega-Hack-Pro-Future/assets/55237683/65711253-bf77-4d74-84a7-adc727d8b418)

It gets installed as a geode mod and everything works except dll mods

**Comment by LukaTV939** [comment]
> I never used geode, but try to uninstall geode and complete a quest, see if it fixed your issues

It crashes when playing with megahack on geode, but when I turn off megahack (because it's just a standard geode mod) it doesn't crash.
That's why I'm making this issue

If you also want to try mhv7 on geode you gonna have to uninstall mh from the installer (settings and extentions won't get deleted), install geode on the gd folder, and then go back to mh installer and select "Latest (Geode)"
Again, the only things that don't work are dll extentions

**Comment by Brittank88** [comment]
> When you install `Geode`, it cleary says: ![image](https://user-images.githubusercontent.com/101340400/272362219-f4f27a43-a3ba-41d1-b911-078eba48123d.png) So geode is quite uncompatible with MH, so absolute can't fix it right now and will not do it

I believe what it's actually saying is that Geode is incompatible with the non-geode version of MHv7 and so you need to first uninstall that, then install Geode, then install the **Geode** version of MHv7.
