### ISSUE TITLE
When I open the Mega Hack v8 menu, my ENTIRE PC PERFORMANCE decreased by alot.

### ISSUE THREAD

**Issue by NoobTrieu** [absolllute/Mega-Hack-Pro-Future#1273]
This did not happen when I first got Mega Hack v7 but when I upgraded to Mega Hack v8 I noticed a big issue. When I press tab to open the Mega Hack v8 menu, it decreased my ENTIRE PC PERFORMANCE alot, you can see this in my screen recording.

https://youtu.be/watch?v=J0TM2FUrTfs

**Comment by Evachermenva** [comment]
Hi
