### ISSUE TITLE
MegaHack v8 crashing when logging in and pressing tab.

### ISSUE THREAD

**Issue by Starflur** [absolllute/Mega-Hack-Pro-Future#1305]
On both versions of the mod (regular and geode ver.), I get prompted to login, but when I do and press tab, the game immediately crashes. I have no clue why, and it has been like this ever since the 2.206 update for MegaHack.

**Comment by Starflur** [comment]
Hey, I got it to work by deleting random Geode mods I had installed.

**Comment by rabaimorp** [comment]
Megahack mobile is unmaintaned, and it only works in 2.1
