### ISSUE TITLE
No Text / Hide Text (GUI Modification?)

### ISSUE THREAD

**Issue by BladeWake** [absolllute/Mega-Hack-Pro-Future#138]
It would be cool if there was a hack to hide any text or words on the screen like ending text or beginning text, it wouldn't work for custom text, and it will probably hide attempts so it would be like a 2 in one hack. I feel like it would be cool and not to hard to code.

**Comment by Brittank88** [comment]
This feels a little arbitrary though - It almost seems like what you're asking for is a subset of a GUI modification system.

In which case, it would be better to either implement the entire system or decide that it lies too far outside the scope of MHv6.

I'm not sure which, that's really up to @absoIute.

**Comment by absoIute** [comment]
not sure of the use of this
