### ISSUE TITLE
YDIS (Y Do I Suck) Integration

### ISSUE THREAD

**Issue by Smartboyy28** [absolllute/Mega-Hack-Pro-Future#145]
To see how long it takes to beat a certain level and see where you die the most because you have to open Ydis every time and I'm lazy.

**Comment by Brittank88** [comment]
> That could be possible but though not something that'd really be priority right now, will talk too Exyl about that if enough people request it though

It seems to be pretty highly valued by everyone: https://twitter.com/_Brittank88/status/1455369221865500675

**Comment by absoIute** [comment]
Alrighty, sounds good will see what I can do for the update after next!
