### ISSUE TITLE
Anti-Cheat Bypass Failure

### ISSUE THREAD

**Issue by dj-v3rsa** [absolllute/Mega-Hack-Pro-Future#147]
I'm using the native speedhack, and it still kicks me out of the level as if I was using CE. I tried AntiCheat Bypass, and that didn't work. I also tried it on Mega Hack v5 and that doesn't seem to work either. Please respond, @absoIute.

**Comment by awesome-coder-d** [comment]
crap never mind i had safe mode on and that was ages ago anyways

**Comment by Brittank88** [comment]
> crap never mind i had safe mode on and that was ages ago anyways

It's fine, we all make mistakes ahaha
