### ISSUE TITLE
"Uncomplete Level" - Reset Orbs/Usercoins?

### ISSUE THREAD

**Issue by Joel055** [absolllute/Mega-Hack-Pro-Future#163]
I suggest adding a function that resets collected orbs and user coins when using the "Uncomplete level" option. Or alternatively, add it as an optional setting alongside the "Uncomplete Level" one. With this, it would be possible to do a full/clean level reset.

Looks weird having coins and max orbs on an uncompleted level, plus it looks strange when recording if you complete it.

**Comment by absoIute** [comment]
Will fix soon!
