### ISSUE TITLE
No BG Flash When Using Teleportal

### ISSUE THREAD

**Issue by Frequencyyy** [absolllute/Mega-Hack-Pro-Future#165]

**Comment by Brittank88** [comment]
Is this a bug? Is this a feature suggestion? Please provide more information next time.

**Comment by Frequencyyy** [comment]
> Is this a bug? Is this a feature suggestion? Please provide more information next time.

Future suggestion

**Comment by absoIute** [comment]
Implemented in v7.1-beta4
