### ISSUE TITLE
MHv7 Makes Game Unstable

### ISSUE THREAD

**Issue by NoNameStuff** [absolllute/Mega-Hack-Pro-Future#222]
Game randomly crashes + makes game lag at random times.

**Comment by absoIute** [comment]
Please send crashlogs

**Comment by patrykchrymecki** [comment]
[crash_1.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7584602/crash_1.txt)
[crash_2.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7584603/crash_2.txt)
Is this what you need?

**Comment by Bango88** [comment]
I am also reviving random crashes constantly, even with all hacks disabled.

**Comment by Brittank88** [comment]
Do you have any extensions that could conflict / cause race conditions? I've heard of cases like this in the past (I actually suffered from a case like that lol)

**Comment by Bango88** [comment]
Nope, I reinstalled multiple times and the problem kept on happening. I eventually switched back to V6 which works fine.

**Comment by absoIute** [comment]
@Bango88 could you send your crashlogs?

@patrykchrymecki reinstall, these look like old crashes that are now resolve

**Comment by Bango88** [comment]
From Event viewer

`Fault bucket 1961090461700623280, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: GeometryDash.exe
P2: 0.0.0.0
P3: 5a13638c
P4: hackpro.dll
P5: 0.0.0.0
P6: 619ee0d9
P7: c0000005
P8: 0052f520
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8a365b87-a3e3-470e-8e2b-99e0cdd9c22b.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_GeometryDash.exe_32836a998859a2e908ba44a1c62265d4b26cf7_59ed2ec6_95308131-ec69-40f5-9c5c-1c393b385fd1

Analysis symbol: 
Rechecking for solution: 0
Report Id: b5807c1d-aec4-4842-9da6-541c294a02a1
Report Status: 268435552
Hashed bucket: a5aa66548ddde6a29b37316276128bb0
Cab Guid: 0`

I'm not sure where else to find crashlogs.

**Comment by Bango88** [comment]
> @Bango88 https://github.com/matcool/small-gd-mods/releases/download/mods/crash-logger.dll
> 
> This will generate crash logs in the GD installation folder.

It doesn't seem to save crash logs. I put the dll in the extensions folder, and I put the minhook thing in the main folder.

**Comment by Brittank88** [comment]
Hm.. interesting. Maybe it saves them somewhere other than what I remember? I'm not sure.

**Comment by absoIute** [comment]
ah thanks, it's a weird crash i'm looking into rn, have no clue what's causing it right and it doesn't seem to generate proper crashlogs :s

**Comment by absoIute** [comment]
fixed in v7.1
