### ISSUE TITLE
Game Crash On Entering Level With Controller

### ISSUE THREAD

**Issue by Nilyfi** [absolllute/Mega-Hack-Pro-Future#233]
I even removed all of my extensions, reinstalled MHV7, still crashes
I hope you can fix it!

**Comment by absoIute** [comment]
Could you send your latest crashlogs from your GD folder here?

**Comment by Nilyfi** [comment]
[crashlog_21-11-24_185802.txt](https://github.com/absoIute/Mega-Hack-Pro-Future/files/7597373/crashlog_21-11-24_185802.txt)
there you go

**Comment by absoIute** [comment]
looks like a better edit bug, try without it

**Comment by Cvolton** [comment]
not the op but this was indeed a known betteredit bug and it was resolved in the latest update, so this issue should be closed
cc @Brittank88
