### ISSUE TITLE
Optimise Show Layout Hack

### ISSUE THREAD

**Issue by DeoxyShocK** [absolllute/Mega-Hack-Pro-Future#241]
I'm not sure if this was an intended outcome but when I enable the Show Layout Hack, although the level appears like a layout, the client still lags as if the level was being played with full detail—especially noticeable when going between parts of a level that look about the same layout-wise but one part does not drop frames while the other actually does even with Show Layout enabled. Also evident when entering an Extremely High Detail level, as it takes much longer to load than if the level was in its "real" layout state.

**Comment by totallyphysicallypossible** [comment]
show layout doesn't seem to actually delete detail, but instead just makes them invisible, which is why rotate triggers still work

**Comment by absoIute** [comment]
Yep, though looking into optimising it more so only the detail used as central rotation objects is kept

**Comment by DeoxyShocK** [comment]
Sounds good, thanks for the amazing work!

**Comment by Nicko2102** [comment]
> Yep, though looking into optimising it more so only the detail used as central rotation objects is kept

I have a mod that basically does this - deletes all details except for rotation centers. If you want more info lmk

**Comment by DeoxyShocK** [comment]
Yes I'm interested in such mod, where can I get it?

**Comment by Nicko2102** [comment]
> Yes I'm interested in such mod, where can I get it?

Dm me Nickooo#9295 i'll answer tomorrow, or just join (this)[https://discord.gg/m9n2tjFqcA]. Brittank/Absolute, if you want me to remove this comment I can.

**Comment by Brittank88** [comment]
> > Yes I'm interested in such mod, where can I get it?
> 
> Dm me Nickooo#9295 i'll answer tomorrow, or just join [this](https://discord.gg/m9n2tjFqcA). Brittank/Absolute, if you want me to remove this comment I can.

I'm fine with it, it's helpful to have some way to do it before the feature is implemented into MH imo.

**Comment by absoIute** [comment]
Optimisations added in v7.1, while there's more still to be done they are still there
