### ISSUE TITLE
Auto-Select Search Bar

### ISSUE THREAD

**Issue by abashir7866** [absolllute/Mega-Hack-Pro-Future#259]
i have a bad habit of starting to type right away instead of clicking onto the search bar so i had the idea of a mod that auto selects the search bar

**Comment by Brittank88** [comment]
Some sort of general smart-select system for inputs could be good but it would need to be highly configurable and not enabled by default in order to be intuitive and not just annoying and seemingly """buggy""" behaviour.

**Comment by succmydecc** [comment]
@abashir7866 that is a sign of autism
