### ISSUE TITLE
The "Low Detail" Option Makes The Background Huge

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#290]
![20211216195754_1](https://user-images.githubusercontent.com/60493629/146486719-201f4bdc-25bb-458d-b454-52ccc5705ffe.jpg)

**Comment by fedqq** [comment]
Same happens to me but instead of making the bg big when turned on, it makes the background small when turned off (only if the game launches with low detail on)

**Comment by absoIute** [comment]
fixed in v7.1 beta3
