### ISSUE TITLE
Speedhack Ship Rotation Freeze

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#359]
When you turn speedhack on at a low value (0.3 and lower), the ship's rotation is very slow and it takes a long time until it actually starts rotating.

https://user-images.githubusercontent.com/60493629/148664162-c28be17d-390f-4ba0-a192-19ac76b20ce2.mp4

.

**Comment by hackercat27** [comment]
this also happens with wave

**Comment by zohnannor** [comment]
That happens with fps higher than 1000 I believe (360*3 = 1080)

**Comment by totallyphysicallypossible** [comment]
This is because MH increases the fps along with the speedhack, if you use 0.3x speedhack then the fps would be 1200, enough for the physics to start messing up

**Comment by absoIute** [comment]
implemented in v7.1
