### ISSUE TITLE
Practice Mode Shortcut

### ISSUE THREAD

**Issue by Nicko2102** [absolllute/Mega-Hack-Pro-Future#393]
Basically self explanatory, add a shortcut keybind that toggles practice mode on/off, same as the restart shortcut

**Comment by NewAlexGamer** [comment]
if you mean restart the level, set a a key to "reset level" in the "shortcuts" section and you're done
about the practice one tho... that would be so cool

**Comment by Nicko2102** [comment]
Thanks :)
To clarify, I know about the restart one - when i said "same as the restart shortcut" i meant that it could be implemented so that it operates in a similar way

**Comment by NewAlexGamer** [comment]
or even better, something that let's you switch from normal to practice and vise versa (however you write that) while maintaining the checkpoints and all

**Comment by Nicko2102** [comment]
oh thats a good idea too, think that should be a separate suggestion though
