### ISSUE TITLE
Megahack Settings Occasionally Wiped

### ISSUE THREAD

**Issue by CyberCat30** [absolllute/Mega-Hack-Pro-Future#620]
I don't know exactly what causes it, and it's somewhat rare, but it's happened to me a lot.

**Comment by NewAlexGamer** [comment]
Ingame settings or megahack setting

**Comment by absoIute** [comment]
Send a screenshot of your GD & extensions folder

**Comment by CyberCat30** [comment]
Here
![extensions](https://user-images.githubusercontent.com/68621086/154836202-0217c5bb-56c9-4718-82a9-d5a63aef40db.PNG)
![gd](https://user-images.githubusercontent.com/68621086/154836216-df39738d-165c-4e17-b23c-02a26de171c5.PNG)

**Comment by CyberCat30** [comment]
This bug hasn't happened to me in quite a while, so it was probably caused by something unrelated to megahack
