### ISSUE TITLE
Adding Features From MHV7 To Extensions

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#647]
i was wondering if you could extend features of mghv7 like the decimal precision to other things, which still relate to it, like run info which displays the percentage you respawned from
this because i completed a level from 0 in practice, what run info was telling me, but it didn't count in normal attempt even tho i had the hack on. so i was about to report another bug when i activated my brain and started testing
![Screenshot_1](https://user-images.githubusercontent.com/86263500/156272538-7ed0055c-2cce-4927-98f6-5e1349d6687a.png)

if not i'll just make another issue asking to integrate the run info into megahack like i did with menu music randomizer, but before this i need to be sure if what is written above can be done or not

**Comment by Brittank88** [comment]
(I'm assuming MGHv7 refers to MHv7, got kinda confused there lol)

**Comment by NewAlexGamer** [comment]
ye i figured, i asked because those mods are generally there and that's it, they're not updated or touched after the release, like it happened with the menu music randomizer, so i wanted to give a try, maybe it could have worked (spoiler: it didn't)
