### ISSUE TITLE
Icons Carrying Over

### ISSUE THREAD

**Issue by fancythedeveloper** [absolllute/Mega-Hack-Pro-Future#657]
I can't tell if this is necessarily a bug or a feature? But either way, it's annoying, and pretty much the only reason why I haven't updated from 7.0.0-beta4 on GDPSs.

Assuming this is a bug, here's the steps to recreate it.

1. Open normal Geometry Dash with at least Mega Hack v7.0.0-beta6 or newer installed. (You can also do this vice-versa, but to make this simple.)

2. Close Geometry Dash

3. Open the Mega Hack Installer and install Mega Hack v7 onto a GDPS. (Not really necessary if you already have it installed there.)

4. Open the GDPS and check either on the Icons menu or check your profile, you should have the icons you had before (even if you had a different icon set for that GDPS).

If this is a feature, an option to turn this off would be nice.

**Comment by fancythedeveloper** [comment]
Replying in case no one has seen it yet.

**Comment by MainConMan** [comment]
It might take a day or 2, but Absolute will eventually see this :)

**Comment by fancythedeveloper** [comment]
> It might take a day or 2, but Absolute will eventually see this :)

Hopefully...

**Comment by fancythedeveloper** [comment]
Insert obligatory bump here.

**Comment by absoIute** [comment]
No need to bump, I will get to it!

**Comment by fancythedeveloper** [comment]
> No need to bump, I will get to it!

Finally you found it, thank you!

**Comment by Brittank88** [comment]
> Finally you found it

For future reference, we don't have to "find" it, GitHub literally serves new issues to us in a notifications list, with issues we haven't yet responded to highlighted.

**Comment by fancythedeveloper** [comment]
Sorry.

**Comment by Brittank88** [comment]
Aw it's okay! Just was letting you know. I figure people don't understand that as they might not be active repo owners.

**Comment by Brittank88** [comment]
@absoIute did you intend to fix this yet?

**Comment by absoIute** [comment]
fix ready for v7.1-beta4!

**Comment by fancythedeveloper** [comment]
Tested it with 7.1-beta4, AND IT ACTUALLY FUCKING FIXES IT. V7 IS NOW ACTUALLY VIABLE FOR GDPSs PAST 7.0-beta4!
