### ISSUE TITLE
Reset Best Run

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#672]
Maybe there can be a feature where you can completely reset your best run.

**Comment by Nicko2102** [comment]
ready for next update, including a reset button (within Best Run options)

_Originally posted by @absoIute in https://github.com/absolllute/Mega-Hack-Pro-Future/issues/428#issuecomment-1030899498_

**Comment by BrownieGamingX5** [comment]
Oops. Didn't know that was in here. Thanks!
