### ISSUE TITLE
gd noclip

### ISSUE THREAD

**Issue by ellipticall** [absolllute/Mega-Hack-Pro-Future#675]
my terminal (when typed sudo and noclip dragged) says permission denied
(secret= my macbook name [i changed it due to personal reasons])

secret@secret-MacBook-Pro ~ % chmod
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
secret@secret-MacBook-Pro ~ % /Users/secret/Desktop/t/NoClip 
zsh: permission denied: /Users/secret/Desktop/t/NoClip
secret@secret-MacBook-Pro ~ % "sudo"
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout]
            [-u user] file ...
secret@secret-MacBook-Pro ~ % /Users/secret/Desktop/t/NoClip 
zsh: permission denied: /Users/secret/Desktop/t/NoClip
secret@secret-MacBook-Pro ~ %

**Comment by RuanauR** [comment]
Uhhhhhhhhhh Mega hack v7 is a Windows/Linux Software I think you mean camila314's mac version.

**Comment by ellipticall** [comment]
no, the absoloute noclip hack is for mac
