### ISSUE TITLE
Auto Music Sync Doesn't Sync With The Endscreen Well

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#682]
When you don't have "Speedhack Audio" turned on in the "Speedhack" menu, have "Auto Music Sync" have sound effects on, the entrance into the end wall and the sound effect that plays when you beat the level doesn't sync correctly. 

Here is a video for what I just explained: https://www.youtube.com/watch?v=y3OevSiR7tI

I had you upload it to YouTube because GitHub's file size is only 10 megabytes large. The file size of the video is about 39 megabytes large, which is nearly 4 times larger than GitHub's file size.

**Comment by absoIute** [comment]
Intended behaviour, auto-music-sync just syncs music to where it's meant to be in the level, use speedhack audio to match audio to your game speed

**Comment by BrownieGamingX5** [comment]
ok
