### ISSUE TITLE
Multiple "Best Run" Texts

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#687]
shows the best <n> runs you got on a level
the format in the screenshot isn't practicable for like 19 best runs, if this gets implemented i'd simply suggest:
best run: 66%
best run 2: 50%
best run 3: 44%
etc...
![Screenshot_1](https://user-images.githubusercontent.com/86263500/160302891-de7fb21c-9d3f-4e2c-8174-0520df1c32e7.png)

**Comment by absoIute** [comment]
Don't want to bloat the status tab too much like that, I feel like the current best run is the best way to go
