### ISSUE TITLE
Editable Decimal Points For Noclip Accuracy

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#689]
Maybe add a feature where you can edit the decimal points for the "Noclip Accuracy" feature to go from 1 through 3. Examples are "95.1%, 95.10%, 95.100%".

**Comment by MainConMan** [comment]
This is similar to #482, but it its also different, so I'm not going to mark as a duplicate. I'll let absolute decide which idea he likes better :)

**Comment by absoIute** [comment]
Will probably just match it to the accurate % option, since that's easier and keeps everything consistent
