### ISSUE TITLE
Add "Ignore Damage" Feature To Noclip

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#690]
Adding a "Ignore Damage" feature to "Noclip" would be so useful. It is technically already noclip by itself. So, why not add to the "Noclip" feature?
![20220329170449_1](https://user-images.githubusercontent.com/60493629/160725701-695dfb2b-5abf-4082-97de-6072db6ad841.jpg)

**Comment by NewAlexGamer** [comment]
so you want an option for an hack that does the same thing the hack does? i'm not getting it

**Comment by MainConMan** [comment]
> so you want an option for a hack that does the same thing the hack does? i'm not getting it

Currently, NoClip won't do anything in the editor, you have to go in the in-game menu and enable Ignore Damage. The suggestion was to add the in-game "ignore Damage" feature to NoClip in megahack.

**Comment by NewAlexGamer** [comment]
oh so he meant for the editor in specific, that's what i wasn't understanding, thanks

**Comment by absoIute** [comment]
Seems redundant as the option is just in the pause menu
