### ISSUE TITLE
Integrated GDDP

### ISSUE THREAD

**Issue by 4-Omega** [absolllute/Mega-Hack-Pro-Future#693]
An in-game version of the GDDP that could have its tiers be separated in different menus

**Comment by NewAlexGamer** [comment]
duplicate of #57

**Comment by MainConMan** [comment]
> duplicate of #57

Didn't notice, Thanks! :)

**Comment by MainConMan** [comment]
Duplicate of #57

**Comment by Brittank88** [comment]
Duplicate of #57

**Comment by MainConMan** [comment]
Duplicate of #57
