### ISSUE TITLE
When I try to install MHv7, it says "MSVCR100.dll was not found". I did extract it

### ISSUE THREAD

**Issue by GDkellen** [absolllute/Mega-Hack-Pro-Future#695]
![what](https://user-images.githubusercontent.com/88408958/161351168-cebddae3-45ef-4e14-b6e4-b0557e9d260e.PNG)

**Comment by MainConMan** [comment]
I believe you just need to install this https://t.co/QNU0za0B4l I could be wrong though.

**Comment by absoIute** [comment]
You need to install https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe

If you're getting an error for MSVCR140.dll as well install https://aka.ms/vs/17/release/vc_redist.x86.exe
