### ISSUE TITLE
700

### ISSUE THREAD

**Issue by 732502** [absolllute/Mega-Hack-Pro-Future#700]
took issue 700 L

**Comment by NewAlexGamer** [comment]
@Nicko2102 can't you ban yet or you need to be a full contributor to the repository

**Comment by Nicko2102** [comment]
> 

I am a contributor but only repo owner can block users

**Comment by NewAlexGamer** [comment]
really? i believe brittank did that once, might be wrong tho

**Comment by Nicko2102** [comment]
he can lock threads and so can i, but he probably just announced the ban

**Comment by NewAlexGamer** [comment]
github should really introduce more "roles" and not let everything to the owner if something like this happens

**Comment by Nicko2102** [comment]
true, gonna lock this convo now tho
