### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by zohnannor** [absolllute/Mega-Hack-Pro-Future#701]
I want to apologize for my recent inactivity on the repo. Hard times have come for me (because of aggravation of Russia-Ukraine situation) and I can't do much about it. I just hope it will end someday and I will continue to be helpful to you all (I really want).

For now, I am sorry for creating this irrelevant issue and flooding the repo tracker.

Fuck war. Peace to everyone.

**Comment by Nicko2102** [comment]
Wishing you the best of luck, hope it ends soon as well ❤️

**Comment by Brittank88** [comment]
@zohnannor We got your back, dw. I hope you stay safe and thank you for finding a way to communicate with us - don't stress about it being a tracker issue. If you ever wanna get into contact with us elsewhere you can find me at `Brittank88#7106`.
