### ISSUE TITLE
Make Hitboxes Show D, J, S, And H Blocks

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#708]
Pretty self explanatory.

**Comment by Nicko2102** [comment]
I like this idea, can be expanded from #464 pretty easily i think

**Comment by NewAlexGamer** [comment]
isn't this a duplicate of #632?

**Comment by MainConMan** [comment]
> isn't this a duplicate of #632?

yes it is! thanks

**Comment by MainConMan** [comment]
duplicate of #632

**Comment by MainConMan** [comment]
Duplicate of #632
