### ISSUE TITLE
Option to change the shape of jump orbs to a hexagon

### ISSUE THREAD

**Issue by Quajeek** [absolllute/Mega-Hack-Pro-Future#713]
Cosmetic option to change the pink, yellow, blue, green, red, and black jump orb shape from a circle to a hexagon.

**Comment by NewAlexGamer** [comment]
Why don't you use a texture pack

**Comment by Quajeek** [comment]
I don't think there would be much to lose by adding the feature. I view it as just another really convenient cosmetic hack.

**Comment by absoIute** [comment]
A change like this requires actually modifying a texture over just hiding something, and I'd rather not start shipping with a bunch of internal textures when something like textureldr exists
