### ISSUE TITLE
New "Level" Category For "Variables" Label

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#716]
i was looking at the variables list for the player and i've noticed a couple that don't really relate to the player, here's the full list for those who don't know
![image](https://user-images.githubusercontent.com/86263500/163433521-dcfff91c-f7a3-497a-ae83-0fdf84d9b8ed.png)
variables like songid, practice and normal %, jumps and attempts should fall in a "level" category instead of the player. i can maybe understand jumps and attempts, but songid and the % have nothing to do with the player other than "the _player_ died here" and, uhhh... "the _player_ is vibing to this songid"

**Comment by absoIute** [comment]
Will drop whole tab at a later point and replace it with something better suited, since it's just a direct port from v5 it's a bit weird
