### ISSUE TITLE
"Size" Variable in "Variables" Label Is Broken

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#717]
i don't know if the "size" variable is supposed to scale the icon, but if it does, it's broken
this is size = 3
![image](https://user-images.githubusercontent.com/86263500/163434019-3bf12a5b-cf5f-41c1-bb4f-5a782762d624.png)

this is size = 0.5
![image](https://user-images.githubusercontent.com/86263500/163434162-0870d9bc-1950-41a1-a6ba-089e018fd126.png)

what is happening is the icon just gets moved up or down and the only thing that gets scaled is the icon trail, the normal trail (fairy trail in my case) stays where it was before
![image](https://user-images.githubusercontent.com/86263500/163434329-46d1d1cb-2118-4d11-8b62-eec5e014f6b3.png)

**Comment by absoIute** [comment]
Expected behaviour for the tab since is just modifies a single size value, will replace the variables tab at some point with a better system, since it's just a bit finicky and weird
