### ISSUE TITLE
Mega hack V7 giving different error in McAfee

### ISSUE THREAD

**Issue by Underkirby** [absolllute/Mega-Hack-Pro-Future#718]
I don`t know if it's a change in the code but now its giving me a different error and i cant trust it.

![Screenshot (278)](https://user-images.githubusercontent.com/95105680/163632583-3c525c09-593b-4f7b-9803-7b11b90160dc.png)

**Comment by Underkirby** [comment]
can you get them to mark it as safe

**Comment by absoIute** [comment]
Just allow the file, it's safe, then whitelist hackpro.dll from McAfee so it doesn't happen again. I've tried contacting them to get the file allowed globally but no luck.
