### ISSUE TITLE
Thread Priority Doesn't Save When Leaving The Game

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#720]
Even with "Auto-Save" on, the "Thread Priority" doesn't save when reopening the game. ![20220420213734_1](https://user-images.githubusercontent.com/60493629/164373161-9efa419c-3cd7-416d-9146-8a72851e26e0.jpg)

I set mine to "Highest", and when I went back into the game, it was reset to "Normal".

**Comment by NefariousIntent2** [comment]
I dont think this is a bug with mhv7 itself. I believe all programs by windows are forced to start at normal threading priority. However, absolute could very easily force highest on runtime

**Comment by Brittank88** [comment]
> I dont think this is a bug with mhv7 itself. I believe all programs by windows are forced to start at normal threading priority. However, absolute could very easily force highest on runtime

Well, unless MHv7 is injecting right at the beginning of launch...isn't it already changing it during runtime?

Absolute knows the implementation better than myself though.

**Comment by absoIute** [comment]
yea it's injected at runtime so can easily change something like that, i just b forgetful
