### ISSUE TITLE
"Stop Triggers on Death" Doesn't Stop Alpha Triggers

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#722]

**Comment by MainConMan** [comment]
It's only supposed to stop move and rotate triggers, but it will be possible to stop alpha triggers when #445 is implemented!

**Comment by NewAlexGamer** [comment]
ops didn't remember that thread, sorry

**Comment by MainConMan** [comment]
It's fine, dw about it :)
