### ISSUE TITLE
(Suggestion) Process Priority and autosave Thread Priority

### ISSUE THREAD

**Issue by DeepResonanceX** [absolllute/Mega-Hack-Pro-Future#723]
since there's an option in v7 to set the game's thread priority, i feel like it would be pretty useful to have an option to change the game's Process priority. maybe not an option to change between normal, above normal, high, etc, but maybe just a single option that's "High Process Priority" that automatically swaps the process priority from Normal to High, to make it easier to change the game's priority without using task manager every time or using an external program to set the default priority to high.

also have both of these options (Thread and Process priority) autosave if possible, so it doesn't have to be changed every time the game is launched.

**Comment by absoIute** [comment]
Process Priority isn't really required since GD is single threaded though will fix auto-saving of it

**Comment by DeepResonanceX** [comment]
oh that's fair, just included that since i personally do notice a difference when using high priority but that's alright, glad to know it'll be fixed tho:)
