### ISSUE TITLE
Frame Rewind

### ISSUE THREAD

**Issue by eckshton** [absolllute/Mega-Hack-Pro-Future#734]
would be a cool feature to have alongside speedhack. i've downloaded some extensions for this, but none of them do it very well

**Comment by Brittank88** [comment]
This technically duplicates #316 however I'm not sure about frame *rewind* so I'll leave it open for now.

**Comment by NewAlexGamer** [comment]
if you mean going "back in time", it's already in the next update as shown in this tweet from him
https://twitter.com/absolllute/status/1502382578996760577?s=20&t=EbHxQTROcYV0dKL83zU2ag

**Comment by CoderQCFromScraatch** [comment]
negative speedhack
