### ISSUE TITLE
Delete Saved Hacks for Mega Hackv7/6.3 via website

### ISSUE THREAD

**Issue by thratisnotavaliable** [absolllute/Mega-Hack-Pro-Future#739]
I turned on No Particles & Now Mega Hack v7 doesn't work for me.
I can't undelete it because before it loads it just crashes.
I checked my antivirus & everything. It's not them.
So I want to know if there is a way to delete your saved data without the hack in the game.

**Comment by NewAlexGamer** [comment]
we need to do some file editing in here now: go to this directory "c:/users/(you)/appdata/local/septima" and in there there should be a file called "options.json", open it and not far done, like line 30 or so you should start seeing the enabled hacks, simply seek for the "no particles" one and delete the line, once you do the game will start with that hack off, you can do this for any hack btw

**Comment by thratisnotavaliable** [comment]
Thank you man!

**Comment by Brittank88** [comment]
@all-contributors please add NewAlexGamer for question.

**Comment by Brittank88** [comment]
Oops, let's try that again

**Comment by Brittank88** [comment]
@all-contributors please add NewAlexGamer for question.
