### ISSUE TITLE
Error 1114

### ISSUE THREAD

**Issue by etherealgd** [absolllute/Mega-Hack-Pro-Future#740]
i tried to inject a dll and it said 1114 pls help

**Comment by NewAlexGamer** [comment]
instead put it in the extensions folder so you won't have the trouble to make the injection every time
also this error is caused because of some power saving options you set on your computer (MAYBE, i'm not even 50% sure about what i've just said, just reading around)

**Comment by etherealgd** [comment]
Oh yeah I remember turning on the  shut everything down at startup setting
whoops

**Comment by etherealgd** [comment]
But when I put it in there it doesn’t do anything

**Comment by etherealgd** [comment]
Also other dlls work so why doesn’t echo work (echo is the dll) (echo is a
free botting tool)

**Comment by NewAlexGamer** [comment]
maybe this is the reason
![image](https://user-images.githubusercontent.com/86263500/168853147-762c5217-917f-4aef-9ba4-cd385eacc3ca.png)

**Comment by etherealgd** [comment]
Nvm I just downloaded a new bot lol and it worked

**Comment by Brittank88** [comment]
Welp, if it's fixed this can be closed.
