### ISSUE TITLE
Force/Disable Song Fade Out (+ ball effect)

### ISSUE THREAD

**Issue by DeepResonanceX** [absolllute/Mega-Hack-Pro-Future#744]
honestly i don't know if anyone else has thought of this or has used it, but i think it'd be pretty cool to have both an option to always force the song "Fade Out" effect on every level you play regardless of if it's toggled on or off, and another to disable it even if the level has been setup to have it on.

it'd probably be cool to play around with some level complete sound effects or just for ppl who prefer one or the other?

also, i think it'd be pretty cool to have a setting to change the ball's rotation speed, to either make it faster or slower, something like a "speed rotation multiplier" so it's still dependant on the speed ur going at instead of a consistent speed that's the same at 1x speed and at 4x speed, since that'd be weird imo.
adding here as to not open another issue just for that lol.

**Comment by NewAlexGamer** [comment]
Keep different suggestions in different issues, having 1 feature per suggestion keeps it organized
Also the ball think is included in #635

**Comment by MainConMan** [comment]
The song fade thing is already suggested in #257 too

**Comment by NewAlexGamer** [comment]
wait @MainConMan the don't fade song is a valid thing tho, doesn't make sense to just close it

**Comment by MainConMan** [comment]
> wait @MainConMan the don't fade song is a valid thing tho, doesn't make sense to just close it

#257 is the same thing though, right? unless im just misunderstanding

**Comment by DeepResonanceX** [comment]
oh the thing is that's a suggestion to only disable the effect, mine was one to disable it and one to always force it on, sorry tho i didn't see it was already suggested lol

**Comment by MainConMan** [comment]
> oh the thing is that's a suggestion to only disable the effect, mine was one to disable it and one to always force it on, sorry tho i didn't see it was already suggested lol

I'll just edit the other suggestion to include the ability to force it too, since they're very similar features. I will give you credit for your idea though :)

**Comment by DeepResonanceX** [comment]
sounds good, tysm!
