### ISSUE TITLE
Logged Out error doesn't disable most hacks

### ISSUE THREAD

**Issue by BlockOG** [absolllute/Mega-Hack-Pro-Future#749]
I have gotten logged out of my account (intentional, not a bug), and I still have most of my hacks on and working...

**Comment by NewAlexGamer** [comment]
when you log out it simply shouldn't let you play, it gives error to me if i try to open gd for example. if you want to disable all hacks delete the "options.json" file in C:\Users\(you)\AppData\Local\Septima, note that uninstalling megahack doesn't delete that file, this means the next time you install it while still having the file you're going to have the hacks you had before uninstalling

**Comment by BlockOG** [comment]
It gives me `Not logged in` and a a button called Dismiss, I just press that button and can use everything fine, just tab does nothing

**Comment by BlockOG** [comment]
Nvm, this bug only happens the first time you get logged out, every time afterwards nothing happens

**Comment by BlockOG** [comment]
This might also be because I'm on linux

**Comment by Brittank88** [comment]
@absoIute Does this behaviour make sense to you? Just want to double check.

**Comment by absoIute** [comment]
Yep been aware of it since launch but it's not really an issue I care to do anything about
