### ISSUE TITLE
Auto Load Comments

### ISSUE THREAD

**Issue by MainConMan** [absolllute/Mega-Hack-Pro-Future#750]
Automatically loads the comments for a level so you don't have to click the "load comments" button.

**Comment by NewAlexGamer** [comment]
options, second page
![image](https://user-images.githubusercontent.com/86263500/170841073-4ef067d9-010b-471d-90d2-a6b9b0686683.png)

**Comment by MainConMan** [comment]
dang never knew about that thanks
