### ISSUE TITLE
MHv7 | Invalid Install Path

### ISSUE THREAD

**Issue by Fabrizio317** [absolllute/Mega-Hack-Pro-Future#751]
![image](https://user-images.githubusercontent.com/63038541/170847317-ad94e9c9-640d-4e32-8928-7634d01119f1.png)

**Comment by NewAlexGamer** [comment]
why is the path below just "GeometryDash.exe" and not the actual absolute path. click on the 3 dots, go in the geometry dash folder, click on the geometrydash.exe and press open, should be fine after that

**Comment by Brittank88** [comment]
Yeah, @NewAlexGamer is correct, it's saying you've chosen an invalid path... because you've chosen an invalid path. Lol

Will reopen if you have anything more to say that shows this is more than user error.
