### ISSUE TITLE
Broken Smart Startpos

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#752]
i actually don't know...
https://www.youtube.com/watch?v=5s73jKJ0uLU

I strongly suggest to watch the video.
i put a startpos near the beginning of the level where there was no portal, speed/gravity change, etc... while having smart startpos. if there was no change before the startpos it should just work as it should, using starting game mode, speed and gravity. once i start the level, instead of being an ufo, it's a wave, if i click, uhhh... things happen, like seriously how broken is that xD

isolating:
also happens with no extensions
also happens with no hacks on except for smart startpos
also happens with just the startpos without the need of the entire level being there as shown in the video

starting settings for the level:
cube behaves normally
ship becomes wave (see wave behaviour)
ball is ball but when you click it permanently teleports underground at y = -15
ufo becomes wave (see wave behaviour)
wave is wave but when you click it permanently teleports underground at y = -10
robot behaves normally
spider is spider but teleports underground at y = -13.5, clicking again will teleport back on ground
speed doesn't affect the problem

startpos can be placed at any high, excluding underground, and it will automatically teleport the player on the ground on the bugged game modes

also why do i have lag spikes now while i record...

**Comment by Brittank88** [comment]
What the heck did I just witness lmao

**Comment by absoIute** [comment]
all fixed next update!
