### ISSUE TITLE
Experimental Mode Noclip | Slope Stop Bug

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#754]
Oh boy...

This is one of the most ANNOYING bugs that has happened to me. When you are on a slope, and you sometimes, do nothing or even holding to do a specific timing, your icon stops at the peak of the slope. It is happening constantly over and over again to me, and I don't know why. I don't know if this could be a vanilla bug, but anyways, I really want a fix for this.

**Comment by Brittank88** [comment]
Is this during noclip or something? I'm not sure how this could possibly happen in normal mode with damage enabled - you'd either pass over as normal, or die.

**Comment by BrownieGamingX5** [comment]
This sometimes happens with no-clip, no matter if it is off or on. I sometimes pass over as normal. Other times, I get stuck and then die.

**Comment by Brittank88** [comment]
That's... strange. What's your refresh rate?

**Comment by BrownieGamingX5** [comment]
It happens with all gamemodes. I have tested this.

**Comment by Brittank88** [comment]
> All gamemodes, really? I've tried everything I know but I can't get any slope bug on the other game modes, what are you doing to get them?

Yeah, @BrownieGamingX5 any way you could record an example with each gamemode or something?

**Comment by BrownieGamingX5** [comment]
Wait a minute. I actually found out on what could possibly causing this. It is noclip. It NEVER happens when I don't have it on. Once again, this happens with every gamemode. NOCLIP must be on to try to replicate this bug.

**Comment by Brittank88** [comment]
So this might be an odd bug with noclip? Does this happen with both versions of noclip (I think there's the standard/classic and then the newer one)?

**Comment by MainConMan** [comment]
Its probably because of experimental mode

**Comment by BrownieGamingX5** [comment]
Ok. So in fact, I have figured it out. It was experimental mode causing it, which could be a bug.

I don't know if this will be fixed or not.

**Comment by absoIute** [comment]
Expected behaviour with experimental, experimental will probably be removed eventually and replaced a proper fix for getting stuck

**Comment by Brittank88** [comment]
> a proper fix for getting stuck

Possible to disable the collision of the specific object the player is colliding with?

**Comment by absoIute** [comment]
Was the idea of experimental, though since that also messed with slope physics it goes a bit deeper (gd physics is horrible)
