### ISSUE TITLE
Practice Checkpoint Switcher

### ISSUE THREAD

**Issue by eckshton** [absolllute/Mega-Hack-Pro-Future#759]
i want to switch practice points like start positions

it would also be convenient if you could somehow save checkpoints for later, but just being able to switch between them would be cool

**Comment by NewAlexGamer** [comment]
isn't this #243?

**Comment by Brittank88** [comment]
This may be a duplicate but I'm not 100% sure yet so I'll treat it as a new enhancement for now.

**Comment by eckshton** [comment]
yeah its basically those. he's already doing it. i checked what people were saying, but missed when absolute said he was gonna do this already in #243.

**Comment by Brittank88** [comment]
Duplicate of #394

**Comment by Brittank88** [comment]
(Just for posterity)
