### ISSUE TITLE
CSS For Mhv7 (Custom HUDS)

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#762]
Allow for custom HUDS (configs that change the GUI of mhv7) to be made and presets: Astolfo, Rise, Moon, ZeroDay, Juul, Azura, Diablo, Vape V4, Sigma, Tenacity, Rose, Novoline. The GUI's can be made using CSS or buttons that add text, an array list, etc. An example of this would be: https://www.youtube.com/watch?v=BS8lrG--uys and https://youtu.be/nkBWMwn5IRg?t=81. Just wait, its an intro. Around the 15 second mark you should see what I mean.

**Comment by NefariousIntent2** [comment]
> "An example of this would be: _video link_ and _video link_" all i see is minecraft gameplay, not being an expert in this i might be wrong tho also this seems a duplicate of #70, more of 156 but apparently that's also a duplicate of 70

basically CSS is a form of code language that is used to develop GUIS. Maybe absolute can add a way to write CSS and change the UI of mhv7 with it.

**Comment by NewAlexGamer** [comment]
sorry yes i knew what css was but i didn't see any example of that in the videos you linked, that's what i meant

**Comment by NefariousIntent2** [comment]
mind assigning brittank or absolute

**Comment by Brittank88** [comment]
I don't think that it would be CSS, but more a set of defined theme variables you can overwrite with theme files.

**Comment by NefariousIntent2** [comment]
Yeah something like that, but absolute should add a ClickGUI option that allows you to select your themes. Along side with that, he should make the Cheat Indicator instead a ModuleList where it will display all the mods in the right, left corner and allow for a custom color to be selected or rainbow

**Comment by NefariousIntent2** [comment]
I made this suggestion because of https://intent.store/

**Comment by absoIute** [comment]
Any customisation to be added would be very basic, probably just being accent & background colour at most so there's not too much of a need for a whole stylesheet system like that
