### ISSUE TITLE
Access violation crashes

### ISSUE THREAD

**Issue by xparadoxical** [absolllute/Mega-Hack-Pro-Future#768]
I regularly get crashes while playing a level. The game is able to crash when it's minimized, when the level is paused and while I'm actively playing the level - so a level just needs to be loaded. Out of like 11 crashes (it's how many I can see in `eventwvr`), only two resulted in any crashlog being written to the GD dir.
[crash-log.log (no stacktrace; collected by matcool's crash-logger)](https://github.com/absolllute/Mega-Hack-Pro-Future/files/8923468/crash-log.log)
[crashlog_22-06-16_111814.txt (has stacktrace; matcool's crash-logger not loaded)](https://github.com/absolllute/Mega-Hack-Pro-Future/files/8923467/crashlog_22-06-16_111814.txt)
Using Windows 11 21H2 22000.675.
I can send all Windows Error Reporting data that was collected, if the two crashlogs aren't worth much.

**Comment by Brittank88** [comment]
> I can send all Windows Error Reporting data that was collected, if the two crashlogs aren't worth much.

If it's not too much effort, you may as well provide the extra information for us to work with.

**Comment by Brittank88** [comment]
Alright, thanks. When Absolute gets a chance he'll look at it.

**Comment by Brittank88** [comment]
Odd. When we get a chance we'll look into it.

**Comment by absoIute** [comment]
Looks like this is an issue with recent Windows 11 versions, patch should be ready for 7.1, soon

**Comment by xparadoxical** [comment]
Didn't get any crash after I updated to v7.1-beta1. Looks fixed to me, thanks.
