### ISSUE TITLE
Save Used Orb/Portal/Pad In Practice

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#771]
when you place a checkpoint in between some portals or right after taking one, it will activate the portal again even tho it might break the level which happens a lot when combinations like orb inside a portal happen, especially with blue orbs and such

![image](https://user-images.githubusercontent.com/86263500/174462671-8b80595b-d2b4-487d-b103-08e9e9b55a9d.png)
if i click this now i should be normal gravity if i wait to enter the portal

![image](https://user-images.githubusercontent.com/86263500/174462680-d8c1e421-4b2f-4b7d-9c6b-7b3d63263e79.png)
now i did the same thing but placed the checkpoint soon after my click and respawned. result is i take once again the portal and basically forces me to buffer clicks, notice the bright colour of the portal indicating the cube activated its effect.

this wouldn't be a problem normally, but on hard levels where clicks like this are basically the core and hardest thing in it, it starts to cause problems and forces me to rewind to a couple of checkpoints back just to attempt the click again

also this completely breaks transitions or parts like this
![image](https://user-images.githubusercontent.com/86263500/174462858-dcb37a53-de98-411e-b93f-58dbf7785c55.png)

**Comment by NefariousIntent2** [comment]
This would also prevent TTV from its "anti practice mode"
