### ISSUE TITLE
Increase Block X/Y Value Decimal Places

### ISSUE THREAD

**Issue by 4jv** [absolllute/Mega-Hack-Pro-Future#776]
yea

**Comment by tyLunar** [comment]
bump

**Comment by NefariousIntent2** [comment]
firstly not decimal limit. but instead the x pos limit

**Comment by 4jv** [comment]
i mean in the value editor, mhv7 can only save up to .XXX

**Comment by absoIute** [comment]
Floats be work like that I'm afraid, can't do much
