### ISSUE TITLE
Separate NONG Folder

### ISSUE THREAD

**Issue by eckshton** [absolllute/Mega-Hack-Pro-Future#778]
it'd be really nice to have resources, appdata, and a separate nong song folder

i swap default songs for nongs all the time, and im running out

**Comment by FunkiestDig** [comment]
I would like to see this as well. The resources folder gets too cluttered and keeping nong songs in a separate folder would make putting them in easier.

**Comment by Brittank88** [comment]
...You guys don't just add files with new custom IDs into `%APPDATA%/GeometryDash`??

You know you don't have to replace default songs in GD, right?

**Comment by Brittank88** [comment]
Basically, you can add your MP3 into the directory where all your downloaded songs go (`%APPDATA%/Local/GeometryDash`), give it any ID you want, and then in-game you type in that ID, and it will *display* as not found or invalid, but if you click where the use song button *should* be, you'll see it actually is still there (underneath the other button that is in its place) and clickable, and the song will be used.

If the MP3 isn't picked up by GD, use a different MP3 downloading website. For example, ytmp3.cc stopped working for GD a while ago - they changed *something* and suddenly the MP3s produced just... aren't seen by GD.

Will close this for now but feel free to reply/reopen if it's not resolved.
