### ISSUE TITLE
Add the different physics at higher fps back when it gets patched in 2.2

### ISSUE THREAD

**Issue by dingleberry12** [absolllute/Mega-Hack-Pro-Future#779]
In 2.2 physics will be the same as 60hz when at higher frame rates, an option to revert this change could maybe be a sub option of the fps bypass.

**Comment by NewAlexGamer** [comment]
i remember rob saying we would be able to switch between new physics and old physics. also it doesn't make sense for him to not do this since a lot of levels would break, again

**Comment by Brittank88** [comment]
Hopefully he also has the game remember which levels use old and new physics by default?

**Comment by Brittank88** [comment]
Anyways, marking as invalid given that 2.2 will probably already implement this.
