### ISSUE TITLE
Small Lines Thickness Messed Up On Different Zooms

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#781]
a lot zoomed out (0.3 thickness)
![image](https://user-images.githubusercontent.com/86263500/175825923-64e91831-905f-4052-947b-7147aed4d4ba.png)

almost gameplay camera (0.3 thickness)
![image](https://user-images.githubusercontent.com/86263500/175825930-6462d8e7-546c-47e6-92e3-ab33fe120f54.png)

this also happens with a low value for the hitbox thickness lines without the need of zooming out at all

**Comment by Brittank88** [comment]
Yeah, this is probably to do with antialiasing or something similar. Not sure how to resolve it myself though. If lines are thin enough they can disappear entirely.

**Comment by absoIute** [comment]
It is, I probably won't do anything about it since it's so minor, more a cocos issue & the hitboxes strokes are drawn inside next update anyway
