### ISSUE TITLE
variable restart time

### ISSUE THREAD

**Issue by eckshton** [absolllute/Mega-Hack-Pro-Future#785]
i have low attention span and want to be able to set the amount of delay between respawns to at least the same as the fast practice reset

**Comment by eckshton** [comment]
i cant do fast reset by pressing esc and clicking because i have to press space and click for green orb double click fyi

**Comment by NewAlexGamer** [comment]
"variables" category, click on "select option" and "player", there search for "respawn time", set it to whatever you want. although you need to repeat this process every time you open the game, you can also set a hotkey to "restart level" like i did so once you press it the level instantly restarts whatever the case. once you get the rhythm, doing the double click after pressing to restart the level won't be a problem. hotkeys are saved even after restarting the game

**Comment by eckshton** [comment]
oh cool ty
