### ISSUE TITLE
Suggestion: auto open megahack menu upon level completion

### ISSUE THREAD

**Issue by ThePandoroxTP** [absolllute/Mega-Hack-Pro-Future#787]
This idea is really meant for people who record and don't stream major level completions. I think it would be nice to have this option as a failsafe in case someone gets so 'in the moment' that they forget to show that the completion wasn't cheated.

**Comment by NefariousIntent2** [comment]
Bad. Whats stopping a user from opening manually and editing to make it look like they arent cheating?

**Comment by ThePandoroxTP** [comment]
How would they do that exactly? There would be cuts in audio if the level doesn't have the music to fade out or if they are on the menu. And typically if the music is the only thing audible and nothing else, no clicks, no commentary, it is seen as suspicious. Ever if the music is set to fade out, there would still be a splice visible from background noise, deleting this out would also be somewhat skeptical.

**Comment by NewAlexGamer** [comment]
get into a green screen level, tab for the menu, now edit the menu out and put it in the final completion

**Comment by ThePandoroxTP** [comment]
huh, not bad!

**Comment by absoIute** [comment]
Not having certain mods enabled in MH is no proof of not cheating, would most likely get annoying and sadly wouldn't prove much
