### ISSUE TITLE
Custom Transitions Being Pixelated

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#788]
Using some of the custom transitions can lead the last scene becoming pixelated. The following custom transitions I have found this bug with are: 

- Tiles
-  Split Rows
- Split Columns
- Fade Top
- Fade Right
- Fade Bottom Left
- Cross Fade

The custom transition I used for this example is "Fade Top". Here is an example on what this looks like in game: 

![20220709190701_1](https://user-images.githubusercontent.com/60493629/178128603-a2ac8ae7-c8fc-442f-8371-de8211f71b70.jpg)

**Comment by oneparsec** [comment]
I also noticed this bug. I don't think it's possible to fix this because Absolute uses Cocos2d's (GD game engine) built-in transitions, so GD is the problem here.

**Comment by absoIute** [comment]
^ issue with cocos2d and such a minor thing I don't think I'll look into it sorry
