### ISSUE TITLE
Question: Buy Megahack with Google Pay

### ISSUE THREAD

**Issue by AxoCode** [absolllute/Mega-Hack-Pro-Future#789]
How to buy megahack v7 pro with google pay?
*Note : I contacted Absolute (discord) a few days ago, but no response*

![image](https://user-images.githubusercontent.com/57800056/178272680-779c7091-deff-467e-b2b6-b749f413c68f.png)
In the website, it says that you can purchase it using either Google Pay, Apple Pay, Mastercard, Visa, and American Express.

But if you click the Checkout button, there is no Google Pay option, only cards.
[*Yes, I open it in Chrome in mobile*](https://user-images.githubusercontent.com/57800056/178272790-9862f48d-ed5d-4a62-96f2-484747f426e7.png)

Edit : I already purchased it with a help of a friend. But I gonna keep it open for other people that want to buy it with google pay

**Comment by absoIute** [comment]
to checkout with Google Pay you need at least one debit/credit card setup in Google Pay and to checkout through Chrome, you can't use Google Play Store vouchers
