### ISSUE TITLE
Game crashing & freezing issues [v7]

### ISSUE THREAD

**Issue by iblowmymind** [absolllute/Mega-Hack-Pro-Future#790]
Hello!

With v7, I can do just about everything I want to just fine, but whenever I want to exit the game (or the game saves) the game will either freeze (not responding at all) or just crash altogether with a "C++ Runtime Exception". In either case, the game will never properly save.

And, when using Borderless Fullscreen, Alt-Tabbing out (even when Fast Alt-Tab is disabled) doesn't actually trigger a save for the game, and V-Sync & Smooth Fix settings don't save (get disabled) when I relaunch with Borderless enabled.

Log: 
```
[12/07/2022 13:25:21]
Oh no! an exception has occurred. anyways heres some info
Module Name: GeometryDash.exe
Exception Code: 0xe06d7363 (idk lol)
Exception Flags: 1
Exception Address: 7636C3A2 (KERNELBASE.dll + 0x12c3a2)
Number Parameters: 3
Stack Trace:
 - C:\WINDOWS\System32\KERNELBASE.dll + 0x12c3a2
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 0x18a19
 - C:\WINDOWS\SYSTEM32\MSVCR120.dll + 0x5dea6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x61557
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x6102d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x6112a
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x637f4
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xe8657
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x74f5b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x292f4
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\hackpro.dll + 0x91d9d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x3d636
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x3d035
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x1131e2
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\hackpro.dll + 0xf7cc1
 - C:\WINDOWS\System32\USER32.dll + 0x411fb
 - C:\WINDOWS\System32\USER32.dll + 0x381ca
 - C:\WINDOWS\System32\USER32.dll + 0x37897
 - C:\WINDOWS\System32\USER32.dll + 0x35a3b
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + 0x4701f
 - C:\WINDOWS\System32\USER32.dll + 0x411fb
 - C:\WINDOWS\System32\USER32.dll + 0x381ca
 - C:\WINDOWS\System32\USER32.dll + 0x37dba
 - C:\WINDOWS\System32\USER32.dll + 0x3b98f
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x74e9d
 - C:\WINDOWS\System32\USER32.dll + 0x3bb9e
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 0x80592
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0x1122e0
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 0xc190b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x261175
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 0x2621fd
 - C:\WINDOWS\System32\KERNEL32.DLL + 0x1fa29
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67a9e
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 0x67a6e
```

It'd be greatly appreciated if you can provide any assistance! Thanks!

**Comment by iblowmymind** [comment]
UPDATE: I've realised that V-Sync / Smooth Fix not getting saved is directly linked to the game savefile not actually being properly saved.

**Comment by iblowmymind** [comment]
UPDATE: Using a 4GB patch on Geometry Dash (https://ntcore.com/?page_id=371) seems to fix the not-saving issue for me, although I don't know why. Probably because my save files are too big? (~70MB each)

**Comment by NewAlexGamer** [comment]
70mb each is a lot, i'm pretty sure getting those numbers slimed a bit would help in various cases, not just the game freezing or crashing. first you might want to try that anyways

**Comment by Brittank88** [comment]
> UPDATE: Using a 4GB patch on Geometry Dash (https://ntcore.com/?page_id=371) seems to fix the not-saving issue for me, although I don't know why. Probably because my save files are too big? (~70MB each)

Yeah, basically, you extended the memory allocation that GD has access to to the maximum for a 32-bit program - 4GB. This is giving it enough memory to handle processing your larger save data.

**Comment by Brittank88** [comment]
> 70mb each is a lot, i'm pretty sure getting those numbers slimed a bit would help in various cases, not just the game freezing or crashing. first you might want to try that anyways

Whilst it's nice to stay relatively clean, I can tell you that it's not necessarily that related - My CCLocalLevels and CCLocalLevels2 files are 159MB each. I don't crash. I do have the 4GB patch though.

**Comment by iblowmymind** [comment]
Until 2.2 gives us proper 64-bit memory adressing, unfortunately we'll be stuck with 2GB-4GB limits. Patching seems to be the only way to deal with heavy-object levels anyway right now, as some levels (>500K objects) require this patch, so using a 4GB patch is probably what most people will want to use. Maybe we can include this kind of behaviour in MHv7? It's incredibly simple to do anyway (you need to set a few hex flags in the PE header), to the point where the MegaHack installer can just take care of it easily. So this is a suggestion?

**Comment by MainConMan** [comment]
> Until 2.2 gives us proper 64-bit memory adressing, unfortunately we'll be stuck with 2GB-4GB limits. Patching seems to be the only way to deal with heavy-object levels anyway right now, as some levels (>500K objects) require this patch, so using a 4GB patch is probably what most people will want to use. Maybe we can include this kind of behaviour in MHv7? It's incredibly simple to do anyway (you need to set a few hex flags in the PE header), to the point where the MegaHack installer can just take care of it easily. So this is a suggestion?
> 

this was already suggested in #13, good idea though!

**Comment by NefariousIntent2** [comment]
> Until 2.2 gives us proper 64-bit memory adressing, unfortunately we'll be stuck with 2GB-4GB limits. Patching seems to be the only way to deal with heavy-object levels anyway right now, as some levels (>500K objects) require this patch, so using a 4GB patch is probably what most people will want to use. Maybe we can include this kind of behaviour in MHv7? It's incredibly simple to do anyway (you need to set a few hex flags in the PE header), to the point where the MegaHack installer can just take care of it easily. So this is a suggestion?

Probably someone can port to a 64 bit before rob does.
