### ISSUE TITLE
Respawn Time Glitch

### ISSUE THREAD

**Issue by githubpub900** [absolllute/Mega-Hack-Pro-Future#792]
when i die sometimes on a level it sets my  respawn time to a weird amount like -1 or nil. when i change it back it works but when i play another level it sets it back to -1 or nil

**Comment by MainConMan** [comment]
Might be a bug with Sai's mod pack, ive heard it causes some issues with it

**Comment by githubpub900** [comment]
ohh makes sense

**Comment by githubpub900** [comment]
"absolute closed this as completed" WHY NOT FIX SUPPORT WITH SAI MOD PACK
