### ISSUE TITLE
Bug: game crashing randomly

### ISSUE THREAD

**Issue by C1intOn110309** [absolllute/Mega-Hack-Pro-Future#793]
log: Time: 2022/07/16 @ 18:39:13
Version: v7-GM1
Code: Access Violation (0xc0000005)
Fault Address: 00330950
Fault Module: GeometryDash.exe
Fault Offset: 00110950

Stack Walk:
GeometryDash.exe + 00110950
GeometryDash.exe + 0010FFD7
GeometryDash.exe + 002030D5
hackpro.dll + 000C0A87
replay-bot.dll + 00002C91
libcocos2d.dll + 001034B6
replay-bot.dll + 00002553
libcocos2d.dll + 000FF435
libcocos2d.dll + 000FFB2D
GeometryDash.exe + 00261175
GeometryDash.exe + 002621FD
KERNEL32.DLL + 00016739
ntdll.dll + 00068FEF
ntdll.dll + 00068FBD

Register States:
EAX: 0
EBX: 0xc7e0101
ECX: 0x12e944c
EDX: 0xc82ccbc
ESI: 0x7fffffff
EDI: 0xc7669d8
ESP: 0xcff8e0
EBP: 0xcff8e8
EIP: 0x770f8fbd
EFLAGS: 00000000001000010000001010010111

Loaded Modules (187):
00220000: GeometryDash.exe
77090000: ntdll.dll
74F90000: KERNEL32.DLL
764B0000: KERNELBASE.dll
76910000: ADVAPI32.dll
76F50000: msvcrt.dll
75750000: sechost.dll
75180000: RPCRT4.dll
75EA0000: SHELL32.dll
7A0C0000: libExtensions.dll
7B030000: libcocos2d.dll
74F10000: msvcp_win.dll
50630000: OPENGL32.dll
75D80000: ucrtbase.dll
76760000: USER32.dll
76C10000: win32u.dll
76C30000: GDI32.dll
74E30000: gdi32full.dll
75370000: combase.dll
62AA0000: glew32.dll
7B5B0000: steam_api.dll
756E0000: WS2_32.dll
7BE00000: fmod.dll
76AC0000: ole32.dll
7B820000: MSVCP120.dll
7BC50000: MSVCR120.dll
5A4C0000: zlib1.dll
7BBC0000: libtiff.dll
10000000: pthreadVCE2.dll
52F50000: GLU32.dll
79D90000: XINPUT9_1_0.dll
7B480000: libcurl.dll
7B1F0000: sqlite3.dll
77020000: WLDAP32.dll
7B460000: MSACM32.dll
74860000: WINMM.dll
53600000: WSOCK32.dll
7BA50000: MSVCR90.dll
7BD40000: MSVCR100.dll
607E0000: dxcore.dll
748A0000: MSVCP140.dll
74910000: VCRUNTIME140.dll
75080000: IMM32.DLL
50000000: XInput9_1_0.dll
7B8A0000: hackproldr.dll
757D0000: CRYPT32.dll
541B0000: msacm32.dll
79C00000: gameoverlayrenderer.dll
76A20000: OLEAUT32.dll
75610000: PSAPI.DLL
750B0000: shcore.dll
72E10000: windows.storage.dll
72A00000: wintypes.dll
784A0000: steamclient.dll
76CF0000: imagehlp.dll
75940000: SETUPAPI.dll
6AE40000: IPHLPAPI.DLL
74980000: VERSION.dll
541E0000: tier0_s.dll
62410000: vstdlib_s.dll
74370000: MSWSOCK.dll
73EB0000: bcrypt.dll
72E00000: Secur32.dll
05300000: SHLWAPI.dll
72D90000: SSPICLI.DLL
6ED70000: CRYPTBASE.DLL
758D0000: bcryptPrimitives.dll
7A110000: hackpro.dll
75620000: COMDLG32.dll
64570000: dbghelp.dll
79DB0000: discord_game_sdk.dll
72AF0000: dwmapi.dll
667E0000: COMCTL32.dll
02CC0000: ktmw32.dll
7B370000: steam.dll
644D0000: dbgcore.DLL
7B000000: CSERHelper.dll
62400000: XInput1_4.dll
72DC0000: cfgmgr32.dll
72BD0000: DEVOBJ.dll
504C0000: inputhost.dll
53480000: CoreMessaging.dll
72D00000: uxtheme.dll
5AD10000: AudioDevProps2.dll
75290000: MSCTF.dll
601D0000: directxdatabasehelper.dll
734C0000: ntmarta.dll
73DA0000: kernel.appcore.dll
76990000: clbcatq.dll
135D0000: nvoglv32.dll
74A70000: WTSAPI32.dll
73540000: msasn1.dll
68CF0000: cryptnet.dll
75240000: WINTRUST.dll
08A60000: nvspcap.dll
71690000: profapi.dll
66D20000: powrprof.dll
667D0000: UMPDC.dll
724B0000: WINSTA.dll
6AE70000: DNSAPI.dll
76E80000: NSI.dll
695E0000: rasadhlp.dll
69510000: fwpuclnt.dll
58B20000: MMDevApi.dll
58770000: AudioSes.dll
603B0000: ProductInfo.dll
538A0000: ASM.Plugin.AudioDevProps2.dll
716D0000: PropSys.dll
60A80000: dxgi.dll
60810000: d3d11.dll
09BE0000: nvldumd.dll
6F850000: CRYPTSP.dll
6F800000: rsaenh.dll
19510000: nvwgf2um.dll
52930000: nvapi.dll
61020000: textinputframework.dll
531E0000: CoreUIComponents.dll
775F0000: winmmbase.dll
50210000: wdmaud.drv
612C0000: ksuser.dll
612B0000: AVRT.dll
541D0000: msacm32.drv
53E70000: midimap.dll
53550000: resourcepolicyclient.dll
0E330000: igd10iumd32.dll
58D40000: igd10um32xe.DLL
666B0000: ncrypt.dll
72240000: NTASN1.dll
080F0000: ControlLib32.dll
08130000: IntelControlLib32.dll
5B400000: igdgmm32.dll
54950000: igc32.dll
548B0000: TextShaping.dll
09530000: DUI70.dll
74140000: Comctl32.dll
01390000: DUser.dll
09AF0000: tiptsf.dll
6FCD0000: edputil.dll
6FC80000: VAULTCLI.dll
779A0000: explorerframe.dll
59D70000: WindowsCodecs.dll
1E4B0000: thumbcache.dll
60150000: dataexchange.dll
5B170000: twinapi.appcore.dll
1EFA0000: Windows.UI.FileExplorer.dll
74A10000: OLEACC.dll
71520000: Windows.FileExplorer.Common.dll
712F0000: iertutil.dll
71130000: Windows.StateRepositoryPS.dll
6FCF0000: windows.staterepositoryclient.dll
1F3C0000: StructuredQuery.dll
77370000: atlthunk.dll
1F460000: Windows.Storage.Search.dll
1F5B0000: Windows.System.Launcher.dll
1F520000: msvcp110_win.dll
1F6A0000: windows.staterepositorycore.dll
6ED30000: MPR.dll
76E90000: coml2.dll
1F830000: p9np.dll
774C0000: LINKINFO.dll
10610000: drprov.dll
1FF80000: ntlanman.dll
1FFA0000: davclnt.dll
722A0000: wkscli.dll
64740000: cscapi.dll
72140000: netutils.dll
2E2B0000: twinapi.dll
74D30000: apphelp.dll
1FFC0000: dlnashext.dll
2E4A0000: PlayToDevice.dll
2E4F0000: DevDispItemProvider.dll
335E0000: buShell.dll
73FD0000: gdiplus.dll
7B280000: NetworkExplorer.dll
33880000: PortableDeviceApi.dll
343F0000: EFACli.dll
74A80000: USERENV.dll
34450000: FileSyncShell.dll
61A90000: WININET.dll
7B610000: ccVrTrst.dll
7B630000: ccLib.dll
7B6E0000: ccSet.dll
34730000: ntshrui.dll
6FAB0000: srvcli.dll
34790000: ActXPrxy.dll
6FA90000: cldapi.dll
7B740000: replay-bot.dll

System:
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
System RAM: 7,279,616 KB
Available RAM: 2,097,024 KB
GPU: Intel(R) UHD Graphics

END OF LOG

**Comment by MainConMan** [comment]
Please send a crash log if you have one!

**Comment by absoIute** [comment]
should be fixed in v7.1 beta
