### ISSUE TITLE
Make "Uncomplete Level" Also Reset Previous New Bests

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#794]
![image](https://user-images.githubusercontent.com/86263500/179413171-ce332594-90cb-473b-9089-71fceb4418f1.png)
this is what happens if you use uncomplete level with better info
i'm suggesting this just to not show those negative "new bests" in the info tab

**Comment by absoIute** [comment]
fixed in v7.1
