### ISSUE TITLE
"Uncomplete Level" Sometimes Doesn't Uncomplete

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#795]
video showcase: https://youtu.be/7o2Lh6iF7Ug

tldr: when you refresh the level it rollbacks at a previous state, not necessarily to the previous one but to last saved state, that's what i think at least

how to replicate: get some percentage, uncomplete, remove the level from saved levels, get back to the level
instead of removing it from the saved levels you could also try and wait a bit to make the game actually check for an update for the reload, haven't tried that tho

**Comment by absoIute** [comment]
fixed in v7.1
