### ISSUE TITLE
Allow Demonlist & Challenge list links to be changed

### ISSUE THREAD

**Issue by CoderQCFromScraatch** [absolllute/Mega-Hack-Pro-Future#796]
I currently run a GDPS and I use mega hack. I want to change the request so it fetches my servers, not the demon list servers. I could change it through a text/config file or DLL hacking. Can this be done in the future? Thanks!

**Comment by fancythedeveloper** [comment]
I mean this could be useful, though wouldn't you need an instance of Pointercrate for this to actually work?

**Comment by CoderQCFromScraatch** [comment]
how does the game usually get the levels?

**Comment by absoIute** [comment]
the demonlist & challengelist are both updated v differently due to different issues there are updating both, adding customisation like that would just cause more complications
