### ISSUE TITLE
Logging out from website

### ISSUE THREAD

**Issue by tyLunar** [absolllute/Mega-Hack-Pro-Future#799]
Hi! So, i factory reset my pc today and i was installing MHv7 it said that my account had to many logins on other devices.

So, instead of whining i thought of a cool idea
Maybe you could logout all devices on the absollute.com website.
My second idea was 2FA with microsoft authentication could be toggled so if there was hackers trying to steal your account they would need ur phone

**Comment by NefariousIntent2** [comment]
2FA is bad. Anyone can sim swap you

**Comment by absoIute** [comment]
already possible through the installer!
2FA I feel isn't worth implementing here though since no sensitive information on the site is stored
