### ISSUE TITLE
New hack: hacks list

### ISSUE THREAD

**Issue by Tulip-0333** [absolllute/Mega-Hack-Pro-Future#806]
Basically, while you are playing it would show a list of hacks that you are using on the top, bottom, left, or right. It could support custom fonts, or not if you want. Only *actual hacks* would be shown, so no cosmetic tab showing. I think the way to code this would be creating a list of activated hacks, every time you activate a hack it would add to the list, then just display the list one way or another, I don't really know how to code sadly. Thanks! Bye.

**Comment by absoIute** [comment]
Cheat Indicator is for this, lists of hacks can just be long and annoying
