### ISSUE TITLE
Make Practice Bug Fix "Support Mirror Portal" A Separate Option

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#807]
let's say you're practicing an old level, silent clubstep for example, and you are at about 44% where the very peculiar ufo part is at, basically up and down corridors with mirror portals every half a second. it's difficult so i place many checkpoints, problem is now i get dizzy every second and it's not easy to practice at all because now the mirror portal activation is saved in the practice bug fix and if i disable the hack now the entire part is broken

**Comment by MainConMan** [comment]
try no mirror or setting mirror speed to 0 in variables

**Comment by NewAlexGamer** [comment]
sure but i'd need to be doing that every time and i'd disable it soon after since it's basically cheating

**Comment by absoIute** [comment]
added ready for v7.1-beta4
