### ISSUE TITLE
Alternative System For Replay To Record

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#808]
i couldn't notice the fact we have to use classic mode for speedhack if we want to record a macro, which isn't that great for the eyes. so i was using my brain power at 90% to figure out an alternative way for replay to not be based on the frames or ticks, idk which one it's based on.
solution: player coordinates! instead of performing at _n_ tick/frame do it at _n_ x-coordinate. we even have decimals for that. this way we are all happy, replay is happy, our eyes are happy

**Comment by Brittank88** [comment]
Yeah, xpos is an existing method and is less accurate than frame fixes.

**Comment by NewAlexGamer** [comment]
oh so it's actually used, never thought of it being less accurate tho with the amount of decimal numbers we have for it

**Comment by Brittank88** [comment]
I think there are other reasons apart from decimal inaccuracy that can cause issues.

**Comment by sinc0s** [comment]
It mainly has to do with float point precision issues. Especially at very high fps, it can become very inaccurate due to the calculations for xpos being more inprecise
