### ISSUE TITLE
"Classic Speedhack" Automatically enabled when I either record or replay a Macro.

### ISSUE THREAD

**Issue by Feanor242** [absolllute/Mega-Hack-Pro-Future#812]
Whenever I try to record or replay a macro, the game automatically enables "Classic Mode" in the Speedhack setting.

**Comment by sinc0s** [comment]
Intended behaviour. Using speedhack without classic mode changes physics and results in inaccurate macros

**Comment by Brittank88** [comment]
Yeah, sinc0s is correct. It has to happen this way.
