### ISSUE TITLE
Transition Time Goes Above 1,000 And Below 0 By Scrolling (Negative)

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#813]
I just saw this, most likely a bug. I'm enjoying the new update though.

I realized on when I scroll down on the "Transition Time" tick box, the time in milliseconds eventually goes into the negatives, affectively giving the animations an instant popup. The same happens with scrolling down, but instead, the time in milliseconds goes over the number 1,000, which is around one second. The more you scroll up, the longer it would take for the menu to popup.

**Comment by absoIute** [comment]
fixed in v7.1-beta4
