### ISSUE TITLE
Bugs With Mega Hack Replay Recording

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#814]
1. The first bug I found with it is that the video is flipped upside down. I have no idea why, but yeah, it happened to me. Here is a screenshot on this bug: 
![image](https://user-images.githubusercontent.com/60493629/180109998-b380d048-3271-41af-b4f7-70bfcd6f8646.png)

2. The second bug I found with this is that there is no audio in the video whatsoever. My volume is up, and I don't hear anything coming from the showcase. 

3. I don't if it is just me but I decided to put this in here. I recorded a 4K + 60 FPS showcase of "Tenkai" by HidekiX by using MegaHackV7.1's recorder. I put the bitrate in the MegaHackV7.1 recorder as 68 megabytes, or about 68,000 kilobytes. I recorded the showcase, and then I realized that the bitrate was about 8 times higher than supposed to. I got a total of 466,789 kilobytes, which was entirely unexpected. Due to the unexpected incredibly high bitrate, the size of the unedited file was 8.31 gigabytes, or 8,927,392,414 bytes in total. And yes this is true. I have no explanation on why that happened, but it was just another strange thing I found with it. 

Overall, the bot is really good. There are just a couple of small problems with it, which is fine by me. Nothing is perfect, and they always will be. Also, for some reason, the audio is entirely separated from the video itself, which I find as awkward.

I'm not 100% sure why this happened to me, but having all of the 3 things I mentioned to be fixed would be cool.

**Comment by sinc0s** [comment]
1. This happens either when the video is not done rendering yet, or there has been a processing issue. If you didn't get a pop-up telling you there was a processing error, you just need to wait until it's done and then the video will be back to normal.
2. The is because the option "Split Audio Track" in the advanced settings is enabled.
3. This is also either due to the video not rendering yet or a processing error.
Also, the audio is separated from the video because of the "Split Audio Track" option. You can turn that off and the video will have the audio as well.

**Comment by BrownieGamingX5** [comment]
Oh ok. Thanks for the tips!

**Comment by Brittank88** [comment]
@all-contributors please add @sinc0s for question

**Comment by BrownieGamingX5** [comment]
@sinc0s Ok. So, I did another recording. The level I recorded this time, was "Silent Club" by blackP2Sfull. I recorded the entire level with MegaHackV7.1's internal recorder. I made sure that the "Split Audio Track" option was off and everything. And still, there was no audio. I am not sure on what is happening here, but it is really strange.

**Comment by Brittank88** [comment]
Have you waited for the post-processing step to complete?

**Comment by BrownieGamingX5** [comment]
Yeah. I'm not sure why.

**Comment by zohnannor** [comment]
For me, when I recorded the level and checked the video, I barely could hear the music. I even sent the vid to my phone to check -- I had to turn my phone volume up to 100% to hear anything. I was recording with low in-game volume though, but it was audible fine.

**Comment by NewAlexGamer** [comment]
Ingame volume shouldn't affect anything. In my case at least I could hear the audio even with ingame volume at 0

**Comment by NewAlexGamer** [comment]
it's already there @Brittank88 , #821

**Comment by Brittank88** [comment]
Oh, no, just didn't see that!
