### ISSUE TITLE
Frame Stepper reactivates after pausing or dying

### ISSUE THREAD

**Issue by Fl1pNatic** [absolllute/Mega-Hack-Pro-Future#818]
I have a keybind that toggles stepping. I die, stepping is on, I press the keybind, it's off. I pause and unpause, stepping is on again. Same with deaths. I think stepping should be disabled until activated manually.

**Comment by NewAlexGamer** [comment]
stepping activates 2 times: the hack itself and the "stepping mode". once the hack is active every time you die it automatically activates the stepping mode

**Comment by Brittank88** [comment]
Considering this a bug, cuz that doesn't seem like very intuitive behaviour.

**Comment by absoIute** [comment]
intended behaviour, add keybind to toggle the mod for the alternate behaviour you're looking for

**Comment by MainConMan** [comment]
> okay, not gonna lie, kinda stupid since using a keybind to toggle it would make backwards stepping just teleport you to the last checkpoint if that's the first thing you do after enabling it

#956
