### ISSUE TITLE
Recorder outputs flipped footage

### ISSUE THREAD

**Issue by raisadesu** [absolllute/Mega-Hack-Pro-Future#822]
When using the settings:
h264_nvenc
100M
yuv420p
3840x2160@60
 -preset slow -rc vbr -qmin:v 19 -qmax:v 14 -maxrate:v 150M -vf colorspace=all=bt709:iall=bt470bg:fast=1

the footage is flipped vertically.
This can be fixed by adding vflip to my ffmpeg args.
I believe the recorder doesn't have the vflip option, or my vf arg overwrites it.

It'd be nice if the recorder automatically appended vfip at the end of my vf arg.

**Comment by sinc0s** [comment]
Have you waited for the video to finish rendering yet? You might have viewed the file before it was fully rendered

**Comment by Brittank88** [comment]
MH is not yet as transparent and clear as it should be about when a video is actually going to be completely finished and post-processed. You may just need to wait a bit longer for it to truly be finished.

**Comment by Brittank88** [comment]
Closing for now, but will reopen if this turns out to be something different.

**Comment by zohnannor** [comment]
Happened to me with long level. It said that rendering was completed but the image is mirrored and there is no sound at all.

**Comment by Brittank88** [comment]
One major issue rn is that "rendering completed" does NOT mean "post processing completed".

It is not very transparent about that at all which definitely needs fixing @absoIute.

**Comment by zohnannor** [comment]
> It is not very transparent about that at all

Yeah, it also said "audio processing failed: too much happened", or something like that, but the reason is unexplained and solution is unknown to me. Those [error] messages definitely should have more info attached to them.
