### ISSUE TITLE
Spambot

### ISSUE THREAD

**Issue by raisadesu** [absolllute/Mega-Hack-Pro-Future#823]
I believe a spambot for MHR would be useful for botting silent levels.
It should have configurable click/release delay separately.

**Comment by sinc0s** [comment]
It is planned for a future update, will probably be one of the first new additions

**Comment by NewAlexGamer** [comment]
isn't this #648 ?

**Comment by Brittank88** [comment]
Yes it is. Closing as duplicate of #648.

**Comment by Brittank88** [comment]
Duplicate of #648
