### ISSUE TITLE
There is no Capture category in Keybinds

### ISSUE THREAD

**Issue by soshok51** [absolllute/Mega-Hack-Pro-Future#831]
The title of the issue speaks for itself. because of this, it is impossible to assign a bind to the screenshot.
![image](https://user-images.githubusercontent.com/78120144/180254349-985a3c09-8b10-4184-ba66-61a557875abc.png)
![image](https://user-images.githubusercontent.com/78120144/180254892-a49b5a3c-5b54-44fa-8cca-69355e7d451d.png)

**Comment by NewAlexGamer** [comment]
![image](https://user-images.githubusercontent.com/86263500/180247278-26f061e2-bd8f-43d9-8e60-a1905f0cbdfe.png)
maybe you mean "no capture" category since the screenshot function is there

**Comment by soshok51** [comment]
> ![image](https://user-images.githubusercontent.com/86263500/180247278-26f061e2-bd8f-43d9-8e60-a1905f0cbdfe.png) maybe you mean "no capture" category since the screenshot function is there

thank you for correcting my mistake!

**Comment by Brittank88** [comment]
Should still have matching category names for clarity.

**Comment by MainConMan** [comment]
Fixed in v7.1beta1
