### ISSUE TITLE
system can't find "MSVCR100.dll"

### ISSUE THREAD

**Issue by CF-Trail** [absolllute/Mega-Hack-Pro-Future#832]
![image](https://user-images.githubusercontent.com/106690765/180249322-926ec5c2-f3d4-45ab-b3fc-7288114c73fe.png)
AV is off, tried reinstalling, launching from desktop in folder

**Comment by Brittank88** [comment]
From [JeanineZhang-MSFT](https://docs.microsoft.com/answers/users/3220626/jeaninezhang-msft.html) over at a [Microsoft Q&A Thread](https://docs.microsoft.com/en-us/answers/questions/234239/despite-everything-msvcr100dll-still-missing.html):

```
MSVCR100.dll = Visual C++ 2010 Runtime

I suggest you could try to download the followings:

32 bit: http://www.microsoft.com/download/en/details.aspx?id=5555

64 bit: http://www.microsoft.com/download/en/details.aspx?id=14632
```

Have you tried making sure that version of the runtime is installed?

**Comment by absoIute** [comment]
make sure to install the x86 (32-bit) version https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe
