### ISSUE TITLE
replay bug

### ISSUE THREAD

**Issue by etherealgmd** [absolllute/Mega-Hack-Pro-Future#834]
i have a bug so whenever i replay a macro its speedhacked for some reason???

what does this mean?

**Comment by MainConMan** [comment]
Its very likely because of lag, if the game cant keep up, itll slow it down so the macro doesnt break.

**Comment by etherealgmd** [comment]
yes i know that but i just even click anything on the macro menu not even in a level and its speedhacked?

**Comment by MainConMan** [comment]
Oh weird

**Comment by MainConMan** [comment]
Should be fixed in v7.1 beta1
