### ISSUE TITLE
Unable To Enter Timeless On The New Update

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#835]
For some reason, "Timeless" by Cyrillic becomes unopenable on the brand new update. I also have "Anti-Kick" turned on too. Prior to the new update, I could enter it just fine without problems. I have the 4 GB patch, which still doesn't make sense. I'm not sure on why I can't open the level in the new update, but I could open it fine on the old update.

**Comment by absoIute** [comment]
fixed in v7.1-beta4
