### ISSUE TITLE
No Available Option To Turn On/Off Hitboxes Of Ground Spikes

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#836]
I just found this out. I don't know why it doesn't show up as an option to turn it off and on.

Edit: Also yes, I took a screenshot with F12. The cursor nor the menu shows up when I do that for some reason.

![20220721225146_1](https://user-images.githubusercontent.com/60493629/180372362-dba17941-1faf-450b-a2b7-c138f64d44df.jpg)

**Comment by absoIute** [comment]
ground spikes grouped with the Solids option (like all slopes)
