### ISSUE TITLE
Safe Mode When Using Replay

### ISSUE THREAD

**Issue by Underkirby** [absolllute/Mega-Hack-Pro-Future#838]
ITS MADE ME BEAT BLOODBATH WITH HACKS NOW I CAN'T GET RID OF THOSE ACHIEVEMENTS

**Comment by NewAlexGamer** [comment]
i remind you this is an actual mod menu with actual hacks on it. it was developed in first place for this purpose
also use this to nullify the thing
![image](https://user-images.githubusercontent.com/86263500/180383154-ae829347-dd62-4a90-8b20-16970d1a87cc.png)

**Comment by Underkirby** [comment]
But can't there be a no complete toggle like on noclip

**Comment by NewAlexGamer** [comment]
but ye i wouldn't mind safe mode being automatically enabled when using replay, actually i'd be great

**Comment by Brittank88** [comment]
@Underkirby It's not helpful to all-caps yell at us, so please just don't.

**Comment by Underkirby** [comment]
yeah, I was just annoyed (angry) cause it made me end up hacking bloodbath
and I got like 10 achievements

**Comment by Brittank88** [comment]
> yeah, I was just annoyed (angry) cause it made me end up hacking bloodbath

Here's a good tip: In literally any situation you shouldn't let that spill out into how you act online.

Sorry it happened but you'll find that it's easier resolved if you're calm about it.

**Comment by MainConMan** [comment]
use auto safe mode!
