### ISSUE TITLE
"Frame Stepper" Goes Back More Than 1 Frame

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#857]
https://user-images.githubusercontent.com/86263500/180667199-b7edcf48-8fca-4114-a027-63f15e6c52c7.mp4

here i'm alternating 'a' and 'd', which are respectively back and front. going forwards is fine, but going backwards isn't that fine: it goes back more than what it should (don't mind the random teleport at the middle, you'll """""understand"""" when you'll read the next issue)

**Comment by absoIute** [comment]
fixed in v7.1-beta4
