### ISSUE TITLE
"Frame Stepper" Is Hella Drunk

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#858]
https://youtu.be/MCekj2isR6U

i highly suggest to watch the video, this time i can't explain it(no, the video is not lagging, it's all ingame, every frame you see is me pressing the 2 keys to use the hack)
i originally wanted to report what is now the previous issue to this one, then this started happening while i was showcasing the bug
why am i always the one finding the most weird broken messed up bugs xD

**Comment by Brittank88** [comment]
What a title lmao

**Comment by MainConMan** [comment]
> What a title lmao

ikr lol

**Comment by absoIute** [comment]
fixed in v7.1-beta4
