### ISSUE TITLE
Make The "Uncomplete Level" Option Reset Your Leaderboard Position

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#859]
The screenshot below was hacked. I was doing a noclip run of "AFRICAN CHUNGUS" by pla. I unfortunately hit my noclip button, which turned off noclip. I then died at 49.000%. I clicked the "Uncomplete Level" option to reset my progress. I then check the leaderboard, and boom, my hacked record still remains there. This is a problem I have had for so long, ever since I have gotten MegaHackV6.3. A fix for this could be pretty helpful.

![20220724232251_1](https://user-images.githubusercontent.com/60493629/180711447-afb1bbcc-ca40-47d1-a9bd-d9c8541a9330.jpg)

**Comment by Brittank88** [comment]
A problem is if this is serverside, in which case I'm not sure there is anything MH can do about that.

**Comment by absoIute** [comment]
Yeah, once it's on the server it can't be reverted sadly
