### ISSUE TITLE
"Unfocused FPS" is Bugged When Tabbing Back in

### ISSUE THREAD

**Issue by Fl1pNatic** [absolllute/Mega-Hack-Pro-Future#860]
After alt-tabbing with the hack, and tabbing back in, the game is running at low fps (Presumably the one set in the hack) until you pull up the Mega Hack menu, which fixes it. FPS Bypass doesn't do anything to this.

**Comment by BrownieGamingX5** [comment]
I have seen this before, could be useful if there was a fix for it.

**Comment by CoderQCFromScraatch** [comment]
Also happens to me.

**Comment by CoderQCFromScraatch** [comment]
> I have seen this before, could be useful if there was a fix for it.

a temporary fix is to press tab twice

**Comment by NewAlexGamer** [comment]
shouldn't this be marked as implemented since it got fixed by being replaced with "pause on unfocus"?

**Comment by MainConMan** [comment]
will add implemented when out of beta
