### ISSUE TITLE
Merging Macros Freezes The Game

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#862]
absolute posted a link on twitter to a tutorial for replay, there at 25:12 he explains how to merge macros. i did exactly what he did in the same order and my game has been frozen for about 5 minutes now
also i don't know you but if that's the only way to merge, it's pretty weird to understand

used hacks
![image](https://user-images.githubusercontent.com/86263500/180761772-703634ec-4b02-49dc-a3c0-1a04450849fa.png)

**Comment by absoIute** [comment]
Could you send the macro files you're trying to merge?

**Comment by NewAlexGamer** [comment]
this also happened a long time ago and it's not a problem anymore, maybe. when the weird dual merging thing will be fixed (the mismatched fps thing) i'll get back to silent circles botting and if it happens again i'll send everything needed
