### ISSUE TITLE
Mega Hack v7.1 Noclip Accuracy Deaths Screen Bug

### ISSUE THREAD

**Issue by NoNameStuff** [absolllute/Mega-Hack-Pro-Future#864]
![mega-hack-v7-1-bug](https://user-images.githubusercontent.com/86684246/180823902-07e04d4c-1154-4313-8e4f-20f2dcdb2fe5.PNG)
Weird border and you can't see all of the deaths
NOTE: Closing and reopening the deaths screen does not fix it.

**Comment by CoderQCFromScraatch** [comment]
An easy solution would be able to make the screen scrollable, similar to BetterInfo by Cvolton

**Comment by absoIute** [comment]
Fixed in v7.1-beta3
