### ISSUE TITLE
make good accuracy

### ISSUE THREAD

**Issue by githubpub900** [absolllute/Mega-Hack-Pro-Future#866]
bot = inaccurate, rbot better

**Comment by MainConMan** [comment]
![image](https://user-images.githubusercontent.com/95152593/180864076-a206d542-0c6a-4b39-9f57-45480d69ef67.png)
use this

**Comment by CoderQCFromScraatch** [comment]
i call that a brain issue

**Comment by NefariousIntent2** [comment]
> ![image](https://user-images.githubusercontent.com/95152593/180864076-a206d542-0c6a-4b39-9f57-45480d69ef67.png) use this

Frame Fixes is basically accuracy fix or ++. Its a physic changer

**Comment by NefariousIntent2** [comment]
also rbot can't compare since it isn't a physic changing bot

**Comment by githubpub900** [comment]
YES IT IS, problay the most buggy one tho

**Comment by githubpub900** [comment]
not any other rbot, the rbot by rewarny, becuz ya

**Comment by githubpub900** [comment]
wait, u thought i was talking about replay bot, im not, im talking about a bot thats actually called rbot
