### ISSUE TITLE
Bug with GD's logo

### ISSUE THREAD

**Issue by TesseractGitHub** [absolllute/Mega-Hack-Pro-Future#873]
When opening the game, Robtop's logo and GD's logo are broken 
![image](https://user-images.githubusercontent.com/109483123/181057773-57ef97af-fdc8-4f34-a825-6072eecedb74.png)
![image](https://user-images.githubusercontent.com/109483123/181057816-09ab9090-9219-41ba-98bf-4821927a8892.png)

**Comment by Brittank88** [comment]
Logo be looking like my savings (cut in half)

**Comment by MainConMan** [comment]
> Logo be looking like my savings (cut in half)

LMAOOO

**Comment by TesseractGitHub** [comment]
> some bug with a plist, you do not seem to be using textureldr

Texturedlr does not fix anything

**Comment by CoderQCFromScraatch** [comment]
idk it is a mega hack issue

**Comment by bruh-bruh8** [comment]
damn what pack is that?

**Comment by TesseractGitHub** [comment]
Custom background

**Comment by absoIute** [comment]
Looks like an issue with your textures, not MH
