### ISSUE TITLE
Pressing The Noclip Accuracy Button On The Endscreen Crashes GD

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#876]
For some reason, my game crashes every time I do this. It doesn't matter when it is from 0% or a start position. It just crashes my game. 

When I had the first beta of MegaHackV7.1, this has never happened to me. Mostly likely could be a bug from the new update.
https://user-images.githubusercontent.com/60493629/181129791-d2145ba5-54b1-4b68-9d66-47ea5573408f.mp4

**Comment by MainConMan** [comment]
It happens only when you have a lot of deaths I believe

**Comment by absoIute** [comment]
Fixed in v7.1-beta3
