### ISSUE TITLE
Built In Autoclicker For MegaHack Replay

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#877]
Maybe create a built an actual accurate auto clicker built into MegaHack Replay because most autoclickers are inaccurate most of the time when going through tight gaps. Examples I have found are with OmegaBot. The autoclicker is really accurate, and it works very very well.

**Comment by NewAlexGamer** [comment]
#648

**Comment by MainConMan** [comment]
Duplicate of #648

**Comment by BrownieGamingX5** [comment]
oops lol
