### ISSUE TITLE
"Practice Bug Fix" Bugs With Triggers

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#879]
https://youtu.be/uEKvVPJluHE
basically if you put a checkpoint in the same frame as a trigger activation and respawn, it will activate bug the effect will be halved (from what we can see in the video at least). now i'm understanding why botting keres is so stupid, i was probably placing checkpoints in the worst frames possible. and since botting is all about slow speeds and very specific frame clicks most of the time, this can become a very relevant problem

**Comment by absoIute** [comment]
Fix ready in v7.1-beta4
