### ISSUE TITLE
I have an issue I put my fps at 0 in mega hack v7.1 and now my game is frozen

### ISSUE THREAD

**Issue by Green0Destroyer** [absolllute/Mega-Hack-Pro-Future#880]
I have no idea what to do about this does anyone know how to fix this?

**Comment by Green0Destroyer** [comment]
I fixed it just uninstall your game and then reinstall it

**Comment by totallyphysicallypossible** [comment]
easier fix: go to %localappdata%\Septima, open options.json, find fps and change the value

**Comment by Brittank88** [comment]
Honestly though reopening because MH shouldn't let you do this.

**Comment by MainConMan** [comment]
> Honestly though reopening because MH shouldn't let you do this.

It didn't let me do it, idk why

**Comment by bruh-bruh8** [comment]
💀

**Comment by MainConMan** [comment]
Fixed in v7.1 beta3
