### ISSUE TITLE
Auto Close FFMPEG When Recording Finishes

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#885]
Maybe it could be useful to automatically close ffmpeg once the video is done rendering. The reason why is because if you record in 4K + 60 FPS with a high bitrate (Example: 68,000 Kbps), your CPU and your RAM would be very very high, therefore decreasing your performance. 

The thing with this though is that the fact once the video is done rendering, ffmpeg stays open as a seperate task in the "Task Manager". It is a bit annoying. Could be cool if there was a fix for this.

**Comment by totallyphysicallypossible** [comment]
What do you mean? It closed itself after it finished rendering for me.

**Comment by 1nfernotm** [comment]
how do you think internal renderers work? Obviously they eat ram and cpu because they're literally using them to process the video. if it weren't then it probably wouldn't work as fast. And ffmpeg automatically closes so i have not an idea what you are saying.

**Comment by BrownieGamingX5** [comment]
Well, fuck it then, I'm closing this
