### ISSUE TITLE
Auto BPM

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#891]
Allow for us to set a certain BPM and have lines automactlly generate

**Comment by MainConMan** [comment]
This is already in better edit I believe!

**Comment by NefariousIntent2** [comment]
Where? I dont see it

**Comment by MainConMan** [comment]
![Screenshot_20220805-074536.png](https://user-images.githubusercontent.com/95152593/183071110-e62f7796-289b-46e8-aebc-97a3fe00379a.png)

**Comment by NefariousIntent2** [comment]
huh? i dont see it there

**Comment by MainConMan** [comment]
Join the gd modding server, they should be able to help you! https://discord.gg/MJYEMVfP2K

**Comment by Brittank88** [comment]
Why is the button just wildin' like that
