### ISSUE TITLE
Show Hitboxes/Trajectory is no longer accurate

### ISSUE THREAD

**Issue by totallyphysicallypossible** [absolllute/Mega-Hack-Pro-Future#893]
![image](https://user-images.githubusercontent.com/94307704/181874804-eb912096-0e9c-4ad4-ab45-79e0e39e8c34.png)

**Comment by MainConMan** [comment]
Show Trajectory has never been 100% accurate. The hitboxes are still accurate though, you were touching the spikes hitbox.

**Comment by totallyphysicallypossible** [comment]
> The hitboxes are still accurate though,
in my opinion, no
![image](https://user-images.githubusercontent.com/94307704/181920142-de6acec1-28e3-409a-8999-c66eb5a13324.png)

**Comment by MainConMan** [comment]
![image](https://user-images.githubusercontent.com/95152593/181936456-6138cb92-caa4-4856-99da-ed61b78d72b6.png)
the hitboxes are touching!!

**Comment by totallyphysicallypossible** [comment]
fair

**Comment by NewAlexGamer** [comment]
well, i mean...
![image](https://user-images.githubusercontent.com/86263500/185259922-38d7c6b6-3a17-4df1-adb7-786fc7ea3b91.png)

**Comment by MainConMan** [comment]
Iirc for a saw to kill you, you either have to be touching the center of the saw, or the corner of your hitbox has to touch the outside of the saw.

**Comment by NewAlexGamer** [comment]
![image](https://user-images.githubusercontent.com/86263500/193312850-5dda3c57-cea7-4cab-aca3-c517a77005bc.png)
ok so neither of the 2 cases is happening here...

**Comment by Brittank88** [comment]
> Iirc for a saw to kill you, you either have to be touching the center of the saw, or the corner of your hitbox has to touch the outside of the saw.

Some way to represent this would be cool tbh
