### ISSUE TITLE
Don't Automatically Turn On "Lock Delta" When Recording A Macro

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#895]
When you are about to start a macro recording, the "Lock Delta" feature gets turned on automatically. This can sometimes be annoying, especially when trying to play levels that require high FPS (Example: 1,000 - 3,000 FPS) or levels that contain a lot of objects that cause a ton of lag (Examples: Black Flag/Storming Summit/And More...)

**Comment by MainConMan** [comment]
Lock delta is needed for the macro to work I believe, try setting tps bypass to the required fps and fps bypass to something lower.

**Comment by totallyphysicallypossible** [comment]
> try setting tps bypass to the required fps and fps bypass to something lower.

I wouldn't recommend that, just turn on real time and be done with it, tps bypass slows down the game either due to it being an old version or poor implementation

**Comment by absoIute** [comment]
It's required, use Real Time to avoid slowdowns
