### ISSUE TITLE
Change "Fast Respawn Time" To "Practice Respawn Time"

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#896]
In this case, "Fast Respawn Time" is literally the same thing as the practice respawn time. Could be changed to fit better
![20220730212400_1](https://user-images.githubusercontent.com/60493629/182009985-2e1b46c4-e45d-41fb-b950-96c6bb30bf94.jpg)
.

**Comment by MainConMan** [comment]
Only if you have the "fast practice reset" option turned on in gd options I think. Maybe it could be changed to "Fast Practice Respawn Time" or something.

**Comment by absoIute** [comment]
not enough space in the label!
