### ISSUE TITLE
Count 100% Noclip Accuracy Runs For Cheat Indicator

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#903]
When you are in noclip accuracy, the cheat indicator obviously shows as red, which acknowledges that you are using noclip. 

But, lets say you are playing through a level with noclip accuracy and cheat indicator. Maybe there could be a feature of where it will stay as green if you have never died before. The moment you take a death in noclip accuracy, the cheat indicator will immediately turn red.

**Comment by sinc0s** [comment]
it's still a hack that is not allowed for demon list so i don't think it should be green at all

**Comment by BrownieGamingX5** [comment]
Ok, fine, this wont be added at all then lmao
