### ISSUE TITLE
Make "Cheat Indicator" Icon Red When "No Mirror" Is Active

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#907]
currently if you enable the "no mirror" hack the cheat indicator won't turn red. why it should? go and play a level with no mirror on and then play it with the hack off, or better, play "hellish spark" which is an easy demon entirely on mirror effect, and i mean ENTIRELY

**Comment by NefariousIntent2** [comment]
*red
