### ISSUE TITLE
Hitbox Rotation bug

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#908]
So, with rotation hack on, i can rotate objects that you aren't supposed to rotate. But, if i show hitboxes while i rotate them, the hitbox just expands.  And that's with the rotation bug on. With it off, the hitbox doesn't move. so, do you mind checking that please? Thank you!

**Comment by NewAlexGamer** [comment]
since it only works locally i don't think a fix for that would matter anyways

**Comment by Unspeakable-Boy** [comment]
> since it only works locally i don't think a fix for that would matter anyways

Then what is the point of the rotation hack?

**Comment by Unspeakable-Boy** [comment]
> > since it only works locally i don't think a fix for that would matter anyways
> 
> What is it used for then?

**Comment by Unspeakable-Boy** [comment]
.

**Comment by totallyphysicallypossible** [comment]
in my opinion, rotation hack really shouldn't be used for anything

**Comment by NefariousIntent2** [comment]
In my opinion, rotation cheat should be removed. since it is client side there is no point

**Comment by Brittank88** [comment]
It is honestly more of a novelty and serves no purpose except for curiosity and local experimentation.

2.2 will make it absolutely obsolete anyways (free scaling) and so by then it could probably be removed.

**Comment by NefariousIntent2** [comment]
> In my opinion, rotation cheat should be removed. since it is client side there is no point

I think absolute said at one point that all hacks must be "server side" or something like that. So this being added sorta gets rid of that
