### ISSUE TITLE
Level Anti-Kick Bypass

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#909]
So, there are a few levels that when I click on them, it acts like it goes into the level, but it just takes me back to the level screen. The same with the editor, but there IS a bypass for that, so can you make the bypass to open a level too? Here’s a video of what happens:

https://user-images.githubusercontent.com/98408012/183159946-5fd17631-aa3e-4234-8ace-a00c91e523ef.mp4

Thank you!

**Comment by BrownieGamingX5** [comment]
Do you have "Anti-Kick" enabled under the "Level" tab? 

Also, some levels that did work with the anti-kick on the gold master version (GM1) worked, but for some reason, the "Anti-Kick" feature was edited a bit, which can sometimes make levels physically impossible to enter or edit in the editor. This is pretty annoying and a fix for this could be useful.

**Comment by NewAlexGamer** [comment]
anti-kick is in the creator tab and only works for entering levels impossible to open in the editor

**Comment by NefariousIntent2** [comment]
It would be useful for having, but I think theres a reason absolute hasn't made an anti kick for levels. They will lag extremely hard, put strain on the CPU and if your pc is bad enough hang the program.

**Comment by Unspeakable-Boy** [comment]
> It would be useful for having, but I think theres a reason absolute hasn't made an anti kick for levels. They will lag extremely hard, put strain on the CPU and if your pc is bad enough hang the program.

Ehh, I think it should be added, and if the level lags, then that person doesn’t use it. But for some people this would be very helpful, so they can at least get into a level. Just because some peoples PC’s stink, doesn’t mean you shouldn’t add it. There is already an Anti kick to enter an editor for a level. Why not to open a level?

**Comment by NewAlexGamer** [comment]
so those with bad pcs like me should risk the health of their own pc to see if using the hack is worth it or not...?

**Comment by Unspeakable-Boy** [comment]
> so those with bad pcs like me should risk the health of their own pc to see if using the hack is worth it or not...?

I’d be glad to test it. My PC isn’t the best, but it’s not bad at all.

**Comment by Unspeakable-Boy** [comment]
> Do you have "Anti-Kick" enabled under the "Level" tab?
> 
> Also, some levels that did work with the anti-kick on the gold master version (GM1) worked, but for some reason, the "Anti-Kick" feature was edited a bit, which can sometimes make levels physically impossible to enter or edit in the editor. This is pretty annoying and a fix for this could be useful.

there is no anti-kick under the level tab... but there should be! Thanks for the feedback!

**Comment by absoIute** [comment]
Fix ready for v7.1-beta4
