### ISSUE TITLE
Make your own icon

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#911]
So, there should be a hack where you can make your own icon, ship, ball, etc. You have the square template (for the icon, and circle template for ball, etc), and add lines and the 2 colors wherever you want them. This would have to be a big, hard project. Is anyone willing to give it a try?

**Comment by BrownieGamingX5** [comment]
Why would this shit would be integrated into MegaHackV7. Because well... that is the most useless thing ever. Like, why would anybody spend the time creating this?

**Comment by totallyphysicallypossible** [comment]
i have no valid argument but please no

**Comment by 1nfernotm** [comment]
It would be better off if this was it's own program, instead of being in MHv7 because only icon creators would actually use it, let alone consider it a hack

**Comment by totallyphysicallypossible** [comment]
While this idea could definitely improve the accessibility of icon making, it also increases the chance of some terrible icons being made, and that i've been fearing as of recent

if anyone is looking to actually try and make an icon and improve, I recommend paint.net

**Comment by NewAlexGamer** [comment]
just open photoshop and put a bunch of lines together

**Comment by MainConMan** [comment]
It would probably be way easier to just use paint.net or Photoshop tbh

**Comment by Unspeakable-Boy** [comment]
Now that I think of it, y’all are right. Case closed.
