### ISSUE TITLE
Can't install MH7.1 (0xc000007b)

### ISSUE THREAD

**Issue by garoomaroo** [absolllute/Mega-Hack-Pro-Future#912]
I can't install Mega Hack v7.1, it keeps giving me the following error code:
![2022-08-06 translated](https://user-images.githubusercontent.com/108290657/183250962-be5b6861-b13b-4971-a8aa-5b575b6b46ef.jpg)
Is this a known error?
(Image was translated using [Yandex Translate](https://translate.yandex.com/ocr))
Original image:

![2022-08-06](https://user-images.githubusercontent.com/108290657/183251154-811f1ce3-5912-4c64-b1c4-097a3090aec6.png)

**Comment by garoomaroo** [comment]
Nevermind, just found out how to fix this.

**Comment by Brittank88** [comment]
> Nevermind, just found out how to fix this.

You should post how you fixed this for the sake of others.

**Comment by absoIute** [comment]
Usually installing https://aka.ms/vs/17/release/vc_redist.x86.exe & https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe will fix it for others!

**Comment by qwertybli1** [comment]
> Nevermind, just found out how to fix this.

how.I too have this problem

**Comment by qwertybli1** [comment]
> Usually installing https://aka.ms/vs/17/release/vc_redist.x86.exe & https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe will fix it for others!

i install this but it didnt work
