### ISSUE TITLE
custom folders for hacks

### ISSUE THREAD

**Issue by eckshton** [absolllute/Mega-Hack-Pro-Future#923]
there are a lot of hacks now (level folder literally has scrollbar)
itd be cool if i could make my own folders which only include the ones that i want

i know i can minimize some tabs, but itd be way cool to only have to look at what i want to look at instead of all hacks at once, and even all level hacks. also having all the ones i want in one list instead of in different folders.

**Comment by MainConMan** [comment]
you could use favourites tab!

**Comment by Brittank88** [comment]
I still feel like a dockable windows system is more versatile but this could help in the meantime?

**Comment by eckshton** [comment]
uh yeah i forgot favorites existed my bad
