### ISSUE TITLE
Present Palette Of Objects From A Specfic Version + Level Version Checker

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#927]
This checks if the blocks in the level existed in such version. A very useful tool for creating old-styled levels

**Comment by Brittank88** [comment]
Oh, this is actually a sick idea. Even better would be to only present the palette of objects available for the specified version.

**Comment by Brittank88** [comment]
Although a checker tool would also be good for verification purposes (E.g. 1.6 building comps, etc.)

**Comment by MainConMan** [comment]
I believe this feature is in better info, but i could be wrong.

**Comment by NefariousIntent2** [comment]
@MainConMan it only shows the version the date is uploaded, but this would be cool

**Comment by MainConMan** [comment]
Oh ok, that makes sense then!

**Comment by NefariousIntent2** [comment]
Wait, let me check.

**Comment by NefariousIntent2** [comment]
Nevermind, you confused the betterinfo for version uploaded on that date. It doesn't do what i have suggested above

**Comment by NefariousIntent2** [comment]
> Oh, this is actually a sick idea. Even better would be to only present the palette of objects available for the specified version.

This would make it 100x easier and discards my original idea of checking a level objects

**Comment by NefariousIntent2** [comment]
Actually absolute, you can add the level version checker too for already existing old-styled levels

**Comment by NefariousIntent2** [comment]
And also another feature for removing objects that go outside a selected version (e.g. if i place a orange orb in the level and then select version 2.0, it will auto delete the orange orb (with conformation) even better would be create a copy of the level without the orange orb

**Comment by NefariousIntent2** [comment]
Also change the physics with level checker, e.g. 1.9 will allow for unnerfed silent club orbs (without clicking 3 times)

**Comment by NefariousIntent2** [comment]
@MainConMan can you assign approved or considering label?

**Comment by MainConMan** [comment]
> @MainConMan can you assign approved or considering label?

Thats for Absolute to do

**Comment by NefariousIntent2** [comment]
Oh ok

**Comment by NefariousIntent2** [comment]
Absolute whats ur opinion on this?

**Comment by absoIute** [comment]
I believe HJfod is working on something like this for BetterEdit, so I probably won't work on it here

**Comment by NefariousIntent2** [comment]
> I believe HJfod is working on something like this for BetterEdit, so I probably won't work on it here

Huh? Wheres proof?

**Comment by NefariousIntent2** [comment]
I have searched GD modding under the tags "palette" "specific version" "old version" level version checker" "version checker". No results show up. But if he is working, can you please tell him to add these specific tools bundled inside whatever he is making. Thanks!

1. Change Physics
2. Delete Objects that aren't in a specific version of the game
3. Level Version Checker (tells you what version you are on with the objects)

**Comment by NefariousIntent2** [comment]
> I believe HJfod is working on something like this for BetterEdit, so I probably won't work on it here

@absoIute wheres proof?
