### ISSUE TITLE
Deactivating Record/Replay Macro Sometimes Doesn't Turn Off Lock Delta/Classic Mode Speedhack

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#928]
when you stop recording or replaying a macro it will automatically turn off lock delta and the classic mode for speedhack which are needed for replay to work. but sometimes either lock delta or classic mode stay active, if not both

**Comment by absoIute** [comment]
If you've enabled them manually before-hand they won't turn off

**Comment by NewAlexGamer** [comment]
sure, but i've never enabled them manually, never touched them

**Comment by absoIute** [comment]
Oh yea can fix that issue then
