### ISSUE TITLE
Start Level at Any Precent

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#931]
So if you need to practice a part of a level without copying the level and placing start pos, then in the hack put what % (you can add a decimal, if you want) of the level you want to practice. So when you play the level, you’ll be at the % you wanted to be at. There is a disable progress option, so if you die, no new best or orbs. Thank you!

**Comment by MainConMan** [comment]
How would the game know where to place the player?

**Comment by Unspeakable-Boy** [comment]
> How would the game know where to place the player?

Oh that’s a good point.

**Comment by NefariousIntent2** [comment]
Not only that, just use copy hack and place a start position wherever you are. Also you can just use variables.
