### ISSUE TITLE
Better Macros

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#932]
Every time I beat an extreme demon in practice mode while recording a macro, and it takes me like an hour to do, I replay it, and I die at like 10%. It’s very frustrating and it’s happened a lot. Is it possible to fix?

**Comment by BrownieGamingX5** [comment]
Do you have "Auto Kill" enabled in the "Level" tab? That could most likely be the reason why. If it isn't, then, I don't know unfortunately.

**Comment by MainConMan** [comment]
Use accuracy fix

**Comment by absoIute** [comment]
As practice bug fix gets better so will the bots vanilla accuracy, though use Frame/Click Fix for even better accuracy
