### ISSUE TITLE
"No Robot Fire" option

### ISSUE THREAD

**Issue by DeepResonanceX** [absolllute/Mega-Hack-Pro-Future#934]
Add an option to remove the robot fire texture shown when jumping.

![Screenshot_2022-08-11-18-38-26-04](https://user-images.githubusercontent.com/93071331/184260045-f2a068b5-0c2a-4107-8206-36391315fd20.jpg)

I know this can be done with texture packs but an option to just easily toggle it on or off without the need to change ur texture pack would be better imo.

**Comment by Unspeakable-Boy** [comment]
You know, that’s not a bad idea! I hope this makes it! 👍

**Comment by absoIute** [comment]
added ready for v7.1-beta4
