### ISSUE TITLE
Most Disliked Levels

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#935]
So, there is a “Most Liked Levels” button in the search menu, and ya’ll have already added a demon and challenge list, so how about most disliked levels? Idk why, but it’s just an idea.

**Comment by NefariousIntent2** [comment]
Not physically possible due to rob changing his servers to work differently. Also a duplicate I believe.

**Comment by MainConMan** [comment]
Couldn't find what this is a duplicate of, but since its not possible, im gonna close this anyway
