### ISSUE TITLE
Style Copier

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#940]
Put in a ID, and then it sets the same BG, G, G2, OBJ. Then copies big parts of a level, vibrant parts and puts them in a logical place. Its probably not possible, but enough training could make this suggestion a reality. Since we have an AI playing a level. Custom coding for GD and more

**Comment by NewAlexGamer** [comment]
how did people take the ai so seriously, it's not a thing

**Comment by totallyphysicallypossible** [comment]
Even if this could become a thing, I would heavily be against it as it's basically copying huge chucks of someone else's work.

**Comment by NefariousIntent2** [comment]
Training AI
Humanoid Part
All you need to do is cut the level every frame into individual pixels. Highlight which one is good to place in a level, mark out the bad ones. Do this for hundreds of thousands of styles until the AI becomes good enough to do this on their own
AI Part
Get a level id, and then it will do the humanoid part find the perfect styles and decorate it accordingly.

**Comment by absoIute** [comment]
Not in the scope of MH I'm afraid
