### ISSUE TITLE
Practice Music Hack: Speed triggers that aren't touched cause music desync

### ISSUE THREAD

**Issue by iblowmymind** [absolllute/Mega-Hack-Pro-Future#941]
Hello,

In Practice Music Hack, speed triggers that aren't touched by the player (so they don't take effect, e.g., in decoration or outside level bounds?) make the game think the music's playing in that speed, causing music desync whenever you re-spawn.

Solution: Track speed triggers that the user went through (or save the song's elapsed seconds) to more accurately calculate sync?

This issue isn't specific to v7, btw, as it's been happening in, AFAIK, every version of practice music, even the non-Absolllute ones.

**Comment by MainConMan** [comment]
It's because of corrective music sync I believe. Unchecking the speed portal's the player doesn't touch in the editor should fix the problem, but I can't test if it does rn.

**Comment by iblowmymind** [comment]
Nope, not caused by Corrective Music Sync, tested without it just now. An obvious example for this issue would be in Double Dash, where at the last part, music sync goes ahead because of some 3x speed portals outside level bounds (don't think they're cheecked, and don't think it matters)

This issue was happening in v5 as well, so I don't think this is caused by Corrective Music Sync

**Comment by absoIute** [comment]
It's because of this, uncheck the portal or disable corrective music sync

![image](https://user-images.githubusercontent.com/20018119/184989855-52b39b57-a3a0-4e02-bd72-59a546677a4c.png)
