### ISSUE TITLE
"No Rotation" Doesn't Correctly Reset The Level When Turned Off

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#949]
![image](https://user-images.githubusercontent.com/86263500/184950967-76dd2934-0c25-4647-84b3-3c40b3b7a712.png)
so what's up with this screenshot? well, i'm dead there
also this
![image](https://user-images.githubusercontent.com/86263500/184951047-d85c2dd4-cc05-43c3-aa43-da0e9f840936.png)
some sprites are messed up and hitboxes don't show correctly
how i did this was simply enter the level with the hack on and disable it inside the level and just keep playing without exiting the level
exiting the level solves the problem of course

**Comment by absoIute** [comment]
Not worth fixing since it's so underused & easy to fix in-game
