### ISSUE TITLE
List of cool mhv7 features ive come up with.

### ISSUE THREAD

**Issue by CompanionCubeGD** [absolllute/Mega-Hack-Pro-Future#952]
Ok so first maybe the ability  to record audio with the mega hack v7 recorder. Also  you guys have probably gotten this already but a clickbot. Also maybe add more lists like  #the shitty list or something.

**Comment by NewAlexGamer** [comment]
ye all of those were suggested already

**Comment by BrownieGamingX5** [comment]
Will the click-bot become a thing one day?

**Comment by MainConMan** [comment]
I know the clickbot has been suggested already, and Absolute said he wasn't gonna add it, but I couldn't find where.

**Comment by NewAlexGamer** [comment]
> I know the clickbot has been suggested already, and Absolute said he wasn't gonna add it, but I couldn't find where.

#648

**Comment by MainConMan** [comment]
I thought they meant a click bot that plays a fake click sound for every click in a macro

**Comment by NefariousIntent2** [comment]
> I thought they meant a click bot that plays a fake click sound for every click in a macro

Actually you aren't wrong. A click bot is exactly that, but it could also mean autoclicker.
