### ISSUE TITLE
Item Place Bypass

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#958]
Lets you place an object/item in the non-gridded space. Like under the ground and behind the start area in the creator.

**Comment by NefariousIntent2** [comment]
Again. Not possible.

**Comment by NefariousIntent2** [comment]
Coming back to this however. It is actually possible! The thought had actually crossed my mind. while making the comment
Step 1.) Open Cheat Engine/GameGuardian or whatever cheat software
Step 2.) Have BetterEdit Installed Or Use the Grid
Step 3.) Move a block by 1 and search for the X POS every time
Step 4.) You can set the block to the float limit (this will make it 2x as long as timeless)
Step 5.) Done. But the block doesn't appear to be any farther, however this can be tested via a start pos
Other Info: So yes technically possible. Above Ground and Below Ground do work! Before the editor does work allowing you to have -100% as a run. Lol.
MainConMan you can reopen this. :)

**Comment by MainConMan** [comment]
I also thought it was impossible, I tried a while ago using a similar method (I dont remember exactly how) and it didn't work. Thanks for the info! :D

**Comment by NefariousIntent2** [comment]
> I also thought it was impossible, I tried a while ago using a similar method (I dont remember exactly how) and it didn't work. Thanks for the info! :D

Btw as a start pos, you can get -100% run so you actually complete a level lol

**Comment by absoIute** [comment]
Closing again because this method seems to just work by using values that break a shit ton of things, the object layer is below the ground layer so there's no realistic way of doing this in a way that'd also affect vanilla clients
