### ISSUE TITLE
Object Doesn't Effect where the level is completed.

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#959]
You can lock an object/ group of objects at the end of a level, so when you reach them, the level ends, thinking those objects don't count in the level. But if you don't lock an object, then you will pass that object before it's over. It could be a cool prank, or to add something cool at the end easily.

**Comment by NefariousIntent2** [comment]
So why are you creating a issue about this?

**Comment by NewAlexGamer** [comment]
i think he wanted to straight up explain what this feature would do instead of starting with "what this feature is supposed to be doing is letting you lock [...]"
it's just to make the move trigger trick simpler or just faster without needing to use a move trigger on your own in the first place

**Comment by absoIute** [comment]
Not possible in a way that affects vanilla clients, use move triggers!
