### ISSUE TITLE
The "TPS Bypass Isn't Showing Up When Enabled

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#965]
Another thing about this bug is that the fact that the "TPS" text next to the framerate you are using only shows up when entering back into the game. After the FPS/TPS bypass updates a second time, it returns back to only the "FPS" text for some reason. This was literally the FIRST ever bugs I have noticed with the new update, and I literally saw so many more in the past 2 hours when I was going to report this bug.

**Comment by absoIute** [comment]
TPS won't show up when FPS & TPS are the same, this is intentional, setting TPS to FPS will result in the same thing as the FPS Bypass on its own
