### ISSUE TITLE
Fps counter randomly showing tps counter even when disabled in mhv7 beta 4 

### ISSUE THREAD

**Issue by pokeyjojo** [absolllute/Mega-Hack-Pro-Future#970]
So in the new mhv7 beta. the tps counter would randomly appear next to the fps counter then quickly vanish afterwards. This is very distracting when playing and i have no idea what caused this too start happening. it started right after i updated to v7.1 beta-4 a video is attached showing the issue.  no bypass for fps or tps is on as i have a 240fps moniter. it seems to appear more after you crash

https://user-images.githubusercontent.com/66097741/185452325-04da4ead-33c8-4eed-91a0-cf28380d649c.mp4

fps counter is in bottom left

**Comment by absoIute** [comment]
aware, will fix
