### ISSUE TITLE
Noclip Doesn't Allow Level Completion If Accuracy != 100%

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#971]
if you enable noclip, just noclip, not accuracy, no limits, just noclip, if you don't get 100% accuracy on the level it won't complete the level. no i don't have "auto safe mode" on nor "safe mode" on
99.56% accuracy = won't complete
100% accuracy = will complete
hacks + extensions used in case you need them
![image](https://user-images.githubusercontent.com/86263500/185457398-c74f87be-b994-4565-a119-da45d970db30.png)

**Comment by MainConMan** [comment]
This is intended if you have disable progress enabled in the noclip sub menu, but I'm gonna assume you don't.

**Comment by NewAlexGamer** [comment]
god... why am i blind omg
i shouldn't be trusted when i don't specify every detail...
but in my defence the "disable progress" option is under the "tint on death", which made my brain think everything below was not relevant to the mechanic of the hack itself but just cosmetic. why isn't that in the top section where the 2 options of how the noclip works are (death limit and accuracy limit)
my brain legit ignored whatever was past those 2 options because of that...
sorry for the wasted issue

**Comment by MainConMan** [comment]
Lmao it's all good dude, we all make mistakes sometimes
