### ISSUE TITLE
i get way more lag on mhv7.1 beta4 than i do on all other versions.

### ISSUE THREAD

**Issue by Xplode1709** [absolllute/Mega-Hack-Pro-Future#972]
idek why it happens, smooth fix doesnt work either, so my game is slowing down constantly when i play anything feature-worthy. i would use lock delta + real time but i'm not a fan of lock delta, it feels REALLY choppy when i actually lag. i have no idea what causes this, but i am on windows 11 (might not help but idk it might)
anyway i have nothing else to say really, i have to use 7.0 for now.
is there a way to revert to other beta versions than the latest? i dont actually know, if theres a solution then i would like to know.

**Comment by NefariousIntent2** [comment]
Have you done an action repeatedly that causes lag right after?+

**Comment by Xplode1709** [comment]
not really, i just played levels, and i was constantly lagging. also smooth fix isnt working on 7.0 either so idk wtf is happening

**Comment by NefariousIntent2** [comment]
> not really, i just played levels, and i was constantly lagging. also smooth fix isnt working on 7.0 either so idk wtf is happening

Are the levels high object? Do you have other programs in the background that could force gd to use more ram

**Comment by MainConMan** [comment]
I don't think it's possible to go to a previous beta version, but I could be wrong.

**Comment by Xplode1709** [comment]
ok, so i dont think im lagging that much more, i actually think its fine. and considering smooth fix doesnt work properly on 7.0 either, i think ill make a reddit post about that specifically and close this. im not sure, but i do think theres a slight difference

**Comment by NewAlexGamer** [comment]
i'm pretty sure reddit is way worse than this github repository to be honest

**Comment by NefariousIntent2** [comment]
> ok, so i dont think im lagging that much more, i actually think its fine. and considering smooth fix doesnt work properly on 7.0 either, i think ill make a reddit post about that specifically and close this. im not sure, but i do think theres a slight difference

A reddit post probably wont solve your issue.
