### ISSUE TITLE
[JOKE] 3dash modmenu

### ISSUE THREAD

**Issue by CompanionCubeGD** [absolllute/Mega-Hack-Pro-Future#975]
3dash mod menu when lol. this is a joke if you could not tell

**Comment by NefariousIntent2** [comment]
I'm going to be as nice as possible with my statements. You don't make jokes here. This is a 100% serious github repo. Any jokes will not be tolerated you will be gaven a warning your issue will be closed instantly and the comments will be locked. Repeated offenders will get banned on this github. If you want to make a joke, do it somewhere else. Not here. You are clogging up our issue/suggestion repo and this is not tolerated at all.

**Comment by NefariousIntent2** [comment]
Close this issue.

**Comment by totallyphysicallypossible** [comment]
bro why are you so offended by this like it's one issue LMAO

**Comment by NefariousIntent2** [comment]
> bro why are you so offended by this like it's one issue LMAO

I am not offended. I was just being firm. Sorry if I got a bit heated.

**Comment by CompanionCubeGD** [comment]
:(. ill make it myself

**Comment by CompanionCubeGD** [comment]
cuz dnspy is cool

**Comment by CompanionCubeGD** [comment]
also sorry thought it would be funny

**Comment by NefariousIntent2** [comment]
> cuz dnspy is cool

You don't use dnspy. Please ask other modders god damn.

**Comment by MainConMan** [comment]
Nefarious did say it a bit harshly, but they are right, please don't make joke issues.

**Comment by NefariousIntent2** [comment]
> Nefarious did say it a bit harshly, but they are right, please don't make joke issues.

My pronouns are she/her :)

**Comment by MainConMan** [comment]
> > Nefarious did say it a bit harshly, but they are right, please don't make joke issues.
> 
> My pronouns are she/her :)

Sorry about that, thanks for correcting me!

**Comment by CompanionCubeGD** [comment]
there are no 3dash modders/???

**Comment by NefariousIntent2** [comment]
> there are no 3dash modders/???

💀

**Comment by NefariousIntent2** [comment]
Please stop commenting on this post. Its useless and gives us notifications we don't want.

**Comment by NewAlexGamer** [comment]
> Please stop commenting on this post. Its useless and gives us notifications we don't want.

ye, about that
![image](https://user-images.githubusercontent.com/86263500/186497484-6fcfb20f-46eb-43a1-805b-2d61d42a03c3.png)

**Comment by NefariousIntent2** [comment]
> > Please stop commenting on this post. Its useless and gives us notifications we don't want.
> 
> ye, about that ![image](https://user-images.githubusercontent.com/86263500/186497484-6fcfb20f-46eb-43a1-805b-2d61d42a03c3.png)

Well....

**Comment by CompanionCubeGD** [comment]
let this thread die i said I was sorry please 💀
