### ISSUE TITLE
Mega hack account gifting (idk if its legal lol)

### ISSUE THREAD

**Issue by VitaminD2** [absolllute/Mega-Hack-Pro-Future#982]
Hello, I have problem. My friend gave me absolllute account and when i open GD it shows that account linked another user. I dont know what to do, so can i have help?

**Comment by NefariousIntent2** [comment]
> Hello, I have problem. My friend gave me absolllute account and when i open GD it shows that account linked another user. I dont know what to do, so can i have help?

Breaks TOS. But if your friend wasn't with the intent going to use the account its fine. Also ur gd acc doesn't matter.

**Comment by MainConMan** [comment]
Click log out all devices in the installer, that should fix the issue! let us know if that works

**Comment by absoIute** [comment]
don't want to allow transferring of licenses like that, licenses are bought on a per-person basis and are non-transferrable
