### ISSUE TITLE
Instant Crash When Respawning Before Respawn

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#984]
basically, respawn character doesnt work

**Comment by NefariousIntent2** [comment]
neither instant respawn great!

**Comment by MainConMan** [comment]
Send crash logs if you can!

**Comment by NefariousIntent2** [comment]
> Send crash logs if you can!

Nah, I already know the issue. Its an access violation

**Comment by NefariousIntent2** [comment]
> Send crash logs if you can!

Yep, just checked crash logs. Echo is causing the issue for whatever reason. Guess i'll switch to replay until KrX fixes this. Although I believe he dropped support for echo and a new dev is underway.

**Comment by absoIute** [comment]
send the crashlogs

**Comment by NefariousIntent2** [comment]
> send the crashlogs
[crashlog_22-06-06_132104.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398334/crashlog_22-06-06_132104.txt)
[crashlog_22-06-06_132355.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398335/crashlog_22-06-06_132355.txt)
[crashlog_22-06-06_132724.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398336/crashlog_22-06-06_132724.txt)
[crashlog_22-06-06_133937.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398338/crashlog_22-06-06_133937.txt)
[crashlog_22-06-06_134225.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398339/crashlog_22-06-06_134225.txt)
[crashlog_22-06-06_134305.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398340/crashlog_22-06-06_134305.txt)
[crashlog_22-06-06_134825.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398341/crashlog_22-06-06_134825.txt)
[crashlog_22-06-06_135149.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398342/crashlog_22-06-06_135149.txt)
[crashlog_22-06-06_135436.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398343/crashlog_22-06-06_135436.txt)
[crashlog_22-06-15_081816.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398344/crashlog_22-06-15_081816.txt)
[crashlog_22-06-16_191703.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398345/crashlog_22-06-16_191703.txt)
[crashlog_22-06-16_193759.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398346/crashlog_22-06-16_193759.txt)
[crashlog_22-07-01_152518.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398347/crashlog_22-07-01_152518.txt)
[crashlog_22-07-06_201622.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398348/crashlog_22-07-06_201622.txt)
[crashlog_22-07-06_201630.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398349/crashlog_22-07-06_201630.txt)
[crashlog_22-07-06_201635.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398350/crashlog_22-07-06_201635.txt)
[crashlog_22-07-06_201703.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398351/crashlog_22-07-06_201703.txt)
[crashlog_22-07-09_103934.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398352/crashlog_22-07-09_103934.txt)
[crashlog_22-07-09_103952.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398353/crashlog_22-07-09_103952.txt)
[crashlog_22-07-09_104003.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398354/crashlog_22-07-09_104003.txt)
[crashlog_22-07-09_104007.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398355/crashlog_22-07-09_104007.txt)
[crashlog_22-07-09_104013.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398356/crashlog_22-07-09_104013.txt)
[crashlog_22-07-09_104014.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398357/crashlog_22-07-09_104014.txt)
[crashlog_22-07-09_104015.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398358/crashlog_22-07-09_104015.txt)
[crashlog_22-07-09_104017.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398359/crashlog_22-07-09_104017.txt)
[crashlog_22-07-09_104018.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398360/crashlog_22-07-09_104018.txt)
[crashlog_22-07-09_104034.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398361/crashlog_22-07-09_104034.txt)
[crashlog_22-07-09_104304.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398362/crashlog_22-07-09_104304.txt)
[crashlog_22-07-09_210508.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398363/crashlog_22-07-09_210508.txt)
[crashlog_22-07-09_210531.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398364/crashlog_22-07-09_210531.txt)
[crashlog_22-07-09_210618.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398365/crashlog_22-07-09_210618.txt)
[crashlog_22-07-10_172428.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398366/crashlog_22-07-10_172428.txt)
[crashlog_22-07-12_113913.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398367/crashlog_22-07-12_113913.txt)
[crashlog_22-07-12_131648.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398368/crashlog_22-07-12_131648.txt)
[crashlog_22-07-12_192508.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398369/crashlog_22-07-12_192508.txt)
[crashlog_22-07-19_121738.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398370/crashlog_22-07-19_121738.txt)
[crashlog_22-07-26_110500.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398371/crashlog_22-07-26_110500.txt)
[crashlog_22-07-27_105325.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398372/crashlog_22-07-27_105325.txt)
[crashlog_22-07-27_115505.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398373/crashlog_22-07-27_115505.txt)
[crashlog_22-08-04_121635.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398374/crashlog_22-08-04_121635.txt)
[crashlog_22-08-04_171917.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398375/crashlog_22-08-04_171917.txt)
[crashlog_22-08-06_205840.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398376/crashlog_22-08-06_205840.txt)
[crashlog_22-08-08_105053.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398377/crashlog_22-08-08_105053.txt)
[crashlog_22-08-20_111826.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398378/crashlog_22-08-20_111826.txt)
[crashlog_22-08-20_111915.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398379/crashlog_22-08-20_111915.txt)
[crashlog_22-08-20_172027.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398380/crashlog_22-08-20_172027.txt)
[crashlog_22-08-20_173834.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398381/crashlog_22-08-20_173834.txt)
[crashlog_22-08-20_203612.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398382/crashlog_22-08-20_203612.txt)
[crashlog_22-08-21_114243.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398383/crashlog_22-08-21_114243.txt)
[crashlog_22-08-21_123025.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398384/crashlog_22-08-21_123025.txt)
[crashlog_22-08-21_184738.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398385/crashlog_22-08-21_184738.txt)
[crashlog_22-08-21_184829.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398386/crashlog_22-08-21_184829.txt)
[crashlog_22-08-21_184948.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398387/crashlog_22-08-21_184948.txt)
[crashlog_22-08-22_090847.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398388/crashlog_22-08-22_090847.txt)
[crashlog_22-08-22_125536.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398389/crashlog_22-08-22_125536.txt)
[crashlog_22-08-22_130139.txt](https://github.com/absolllute/Mega-Hack-Pro-Future/files/9398390/crashlog_22-08-22_130139.txt)

**Comment by NefariousIntent2** [comment]
All crashlogs I could find. But the last 5 are relevant as they cause an access violation. I would assume it has to do with the cube loading before and echo just gets in the way of it and causes a crash

**Comment by NefariousIntent2** [comment]
I reported this to echo server too in case KrX or gecks can find a way to fix it.

**Comment by absoIute** [comment]
Yeah looks like it's an issue on Echo's end

**Comment by NefariousIntent2** [comment]
> Yeah looks like it's an issue on Echo's end

Alright. Disabling echo gets rid of the issue

**Comment by NefariousIntent2** [comment]
Replay for now
