### ISSUE TITLE
Megahack Causes My Whole Computer To Freeze and Reset All Data

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#985]
Sometimes when completing a level I experience this freeze. All data and I mean all data are reset. I checked by looking at the computer and the fan just stopped. This shouldn't happen unless PHYSICAL memory was frozen which is impossible unless you enter a dbvm state.

**Comment by absoIute** [comment]
this sounds like an issue with your specific system, not Mega Hack

**Comment by NefariousIntent2** [comment]
> this sounds like an issue with your specific system, not Mega Hack

Well no. Because I had mega hack v7 when it was in its early beta and I didn't had issues with it. I had mega hack for 7 1/2 months now and I haven't had this entire OS softlock until I installed the latest beta of mega hack. I have been using windows for about 5 years now and I haven't had the OS softlock only programs until mega hack was installed. Even though my systems could lead to this, I'd say mega hack is the fault here.

**Comment by absoIute** [comment]
Coincidences like this happen, but I've also had no other reports of this so unless you've got a reliable way of reproducing the issue there's not anything I can do I'm afraid.

**Comment by NefariousIntent2** [comment]
> Coincidences like this happen, but I've also had no other reports of this so unless you've got a reliable way of reproducing the issue there's not anything I can do I'm afraid.

I can prove myself by just recording until a freeze
