### ISSUE TITLE
Nightvision For Dark Parts

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#986]
The background of dark memory is shifted to gray. This is useful for showcases and attempting to learn memory without practice mode

**Comment by sinc0s** [comment]
Layout mode kind of accounts for this, but it would still be cool.

**Comment by NefariousIntent2** [comment]
> Layout mode kind of accounts for this, but it would still be cool.

I mean yes, but this would go well if players want to show a high detail mode but still show the memory

**Comment by MainConMan** [comment]
You could also use hitboxes!

**Comment by absoIute** [comment]
Use Layout Mode or Hitboxes, no need for a mod for this
