### ISSUE TITLE
Rename "Frame Fixes" To "Physic Fixes"

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#989]
Because its better that way and gives a clear inform instead of "frame fixes" is basically accuracy fix but its like TASBOT-worded

**Comment by sinc0s** [comment]
the only problem with this is that click fixes and frame fixes both use physics changing. perhaps you could changing them to "Click Physics Fix" and "Frame Physics Fix" but i feel like that is just too long.

**Comment by NefariousIntent2** [comment]
> the only problem with this is that click fixes and frame fixes both use physics changing. perhaps you could changing them to "Click Physics Fix" and "Frame Physics Fix" but i feel like that is just too long.

Nope, both should be Physics Fix since they don't vary except for how they work

**Comment by NefariousIntent2** [comment]
Bots like aBot, oBot, Echo use both Click and Frame physics fix

**Comment by sinc0s** [comment]
they do vary in how they work. they both change physics, but click fixes does it on every click and release, and frame fixes does it every frame. the distinction here is important and that's why I think the current naming conventions are fine

**Comment by NefariousIntent2** [comment]
> they do vary in how they work. they both change physics, but click fixes does it on every click and release, and frame fixes does it every frame. the distinction here is important and that's why I think the current naming conventions are fine

Exactly. But they still do the same thing. But both have to be used in different situations

**Comment by absoIute** [comment]
They don't do the same thing, the current naming is the clearest way describe when both accuracy fixes are applied
