### ISSUE TITLE
Unnerfed/Nerfed/Old/New Levels

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#993]
For example stereo demoness (the one on majacko account) will have a button right next to it to swap to the unnerfed version.
This is easier then going to compendium, scrolling down and pressing play.
![vgpsvp5i](https://user-images.githubusercontent.com/107162305/186235861-e30750fc-39d7-4cd6-85ab-0405a5ba2b6d.png)

**Comment by NefariousIntent2** [comment]
Also old cataclysm vs new cataclysm too

**Comment by FnigePython** [comment]
Honestly I feel like this would be better as a GD mod than something baked within MH itself

**Comment by NefariousIntent2** [comment]
> Honestly I feel like this would be better as a GD mod than something baked within MH itself

mhv7 is level aspects, so it makes sense here

**Comment by NefariousIntent2** [comment]
Not trying to make a unnerfed version of all levels, just the ones that are popular/rated

**Comment by NefariousIntent2** [comment]
> I understand, but even doing it specifically for the popular levels will take quite a bit of time, and people will most likely give constant suggestions for other levels to be added.

Thats good actually, maybe have a spreadsheet where people can add levels

**Comment by NefariousIntent2** [comment]
> I understand, but even doing it specifically for the popular levels will take quite a bit of time, and people will most likely give constant suggestions for other levels to be added.

Also can you ping me every time so I get notifications?

**Comment by absoIute** [comment]
There's no way of grabbing the old versions from the servers so it'd have to be done manually and that's just not something I want to support if it can't be automated
