### ISSUE TITLE
"Disable Input" Option For Replay

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#994]
this is purely to show off on friends and prank them, nothing else. probably good trolling to do in streams too

**Comment by NefariousIntent2** [comment]
![Uploading vnhhhzu7.png…]()

**Comment by NefariousIntent2** [comment]
I mean it could be called "Disable Input" but block Input is better

**Comment by NewAlexGamer** [comment]
oh god i'm stupid sorry

**Comment by NefariousIntent2** [comment]
> oh god i'm stupid sorry

Its all good :)
