### ISSUE TITLE
Replace The "Level ID" Text With None (Not Uploaded)

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#995]
Maybe there could be a feature of where instead of the "Level ID" text reading as "0", it can instead read as "None". It should make more sense that way than having it to be read as "0".

![image](https://user-images.githubusercontent.com/60493629/186325156-cf48480f-2f9e-4749-b74e-6684bd5af98a.png)

**Comment by NefariousIntent2** [comment]
> Maybe there could be a feature of where instead of the "Level ID" text reading as "0", it can instead read as "None". It should make more sense that way than having it to be read as "0".
> 
> ![image](https://user-images.githubusercontent.com/60493629/186325156-cf48480f-2f9e-4749-b74e-6684bd5af98a.png)

Yep

**Comment by NefariousIntent2** [comment]
> Maybe there could be a feature of where instead of the "Level ID" text reading as "0", it can instead read as "None". It should make more sense that way than having it to be read as "0".
> 
> ![image](https://user-images.githubusercontent.com/60493629/186325156-cf48480f-2f9e-4749-b74e-6684bd5af98a.png)

Brownie do you have a discord? Can you friend me here: VoidNC#9496. I need to have a discussion with you

**Comment by absoIute** [comment]
Will just hide the label when it doesn't apply

**Comment by NefariousIntent2** [comment]
> Will just hide the label when it doesn't apply

Theres a new label?
