### ISSUE TITLE
Allow Changing Title After Upload

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#997]
Automate the process of creating a copyable then upload the changed name, and finally delete the already uploaded level

**Comment by MainConMan** [comment]
Doesn't seem like it would be worth adding as a feature to mh since it's easy to do manually, but up to absolute.

**Comment by NefariousIntent2** [comment]
> Doesn't seem like it would be worth adding as a feature to mh since it's easy to do manually, but up to absolute.

Oh.. ok
